---
apiVersion: v1
kind: Service
metadata:
  name: tempo-query-frontend
  labels:
    app.kubernetes.io/name: tempo-query-frontend
    app.kubernetes.io/component: query-frontend
    prometheus.io/service-monitor: "true"
spec:
  type: ClusterIP
  ports:
  - name: http-metrics
    port: 3100
    targetPort: 3100
  - name: grpc
    port: 9095
    protocol: TCP
    targetPort: 9095
  selector:
    app.kubernetes.io/component: query-frontend
