---
# Source: tempo-distributed/templates/compactor/servicemonitor-compactor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tempo-query-frontend
  labels:
    app.kubernetes.io/name: tempo-query-frontend
    app.kubernetes.io/component: query-frontend
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
    - observability
  selector:
    matchLabels:
      app.kubernetes.io/name: tempo-query-frontend
      app.kubernetes.io/component: query-frontend
    matchExpressions:
    - key: prometheus.io/service-monitor
      operator: In
      values:
      - "true"
  endpoints:
  - port: http-metrics
    relabelings:
    - sourceLabels: [job]
      replacement: "observability/query-frontend"
      targetLabel: job
    scheme: http
