---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app: loki
    app.kubernetes.io/part-of: loki

resources:
- backend/clusterrole.yaml
- backend/clusterrolebinding.yaml
- backend/poddisruptionbudget-backend.yaml
- backend/query-scheduler-discovery.yaml
- backend/service-backend-headless.yaml
- backend/service-backend.yaml
- backend/statefulset-backend.yaml
- gateway/configmap-gateway.yaml
- gateway/deployment-gateway-nginx.yaml
- gateway/ingress-gateway.yaml
- gateway/service-gateway.yaml
- loki-canary/daemonset.yaml
- loki-canary/service.yaml
- loki-canary/serviceaccount.yaml
- read/deployment-read.yaml
- read/poddisruptionbudget-read.yaml
- read/service-read-headless.yaml
- read/service-read.yaml
- results-cache/poddisruptionbudget-results-cache.yaml
- results-cache/service-results-cache-headless.yaml
- results-cache/statefulset-results-cache.yaml
- write/poddisruptionbudget-write.yaml
- write/service-write-headless.yaml
- write/service-write.yaml
- write/statefulset-write.yaml
- config.yaml
- runtime-configmap.yaml
- service-memberlist.yaml
- serviceaccount.yaml

patches:
- patch: |-
    - op: remove
      path: /spec/template/spec/affinity
  target:
    kind: Deployment
- patch: |-
    - op: remove
      path: /spec/template/spec/affinity
  target:
    kind: StatefulSet
