---
##
# Global/Cluster Configuration
##

k3s_cluster_domain: cluster.local

# k3s state (see k3s_valid_states)
k3s_state: installed

k3s_release_version: v1.31.4+k3s1

# Location of the k3s configuration file
k3s_config_file: /etc/rancher/k3s/config.yaml

# Location of the k3s configuration directory
k3s_config_yaml_d_dir: /etc/rancher/k3s/config.yaml.d

# When multiple ansible_play_hosts are present, attempt to cluster the nodes.
# Using false will create multiple standalone nodes.
# (default: true)
k3s_build_cluster: true

# URL for GitHub project
k3s_github_url: https://github.com/k3s-io/k3s

# Skip post-checks
k3s_skip_post_checks: false

# Installation directory for k3s
k3s_install_dir: /usr/local/bin

# Install using hard links rather than symbolic links
k3s_install_hard_links: false

# Enable etcd embedded datastore
k3s_etcd_datastore: false

##
# Systemd config
##

# Start k3s on system boot
k3s_start_on_boot: true

# List of required systemd units to k3s service unit.
k3s_service_requires: []
# List of "wanted" systemd unit to k3s (weaker than "requires").
k3s_service_wants: []
# Start k3s before a defined list of systemd units.
k3s_service_before: []
# Start k3s after a defined list of systemd units.
k3s_service_after: []
# Dictionary of environment variables to use within systemd unit file
# Some examples below
k3s_service_env_vars: {}
#  PATH: /opt/k3s/bin
#  GOGC: 10

# Location on host of a environment file to include. This must already exist on
# the target as this role will not populate this file.
k3s_service_env_file: false

##
# Server Configuration
##

k3s_server: {}
# k3s_server:
#  listen-port: 6443

##
# Agent Configuration
##

k3s_agent: {}
# k3s_agent:
#   node-label:
#     - "foo=bar"
#     - "bish=bosh"

##
# Ansible Controller configuration
##

# Use become privileges?
k3s_become: false

# If true, copy root CA certs from ansible-controller
k3s_copy_ca_certs: true
# Path where to find CA certs
ca_root_certs_path: /usr/local/etc/certs/ca

k3s_inotify_max_user_instances: 2048
k3s_inotify_max_user_watches: 496748
