---
apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-jobservice-env
data:
  CORE_URL: "https://harbor-core:443"
  TOKEN_SERVICE_URL: "https://harbor-core:443/service/token"
  REGISTRY_URL: "https://harbor-registry:5443"
  REGISTRY_CONTROLLER_URL: "https://harbor-registry:8443"
  REGISTRY_CREDENTIAL_USERNAME: "harbor_registry_user"
  JOBSERVICE_WEBHOOK_JOB_MAX_RETRY: "3"
  JOBSERVICE_WEBHOOK_JOB_HTTP_CLIENT_TIMEOUT: "3"
  HTTP_PROXY: ""
  HTTPS_PROXY: ""
  NO_PROXY: "harbor-core,harbor-jobservice,harbor-database,harbor-registry,harbor-portal,harbor-trivy,harbor-exporter,127.0.0.1,localhost,.local,.internal"
  METRIC_NAMESPACE: harbor
  METRIC_SUBSYSTEM: jobservice
  TRACE_SERVICE_NAME: "harbor-jobservice"
  TRACE_ENABLED: "true"
  TRACE_SAMPLE_RATE: "1"
  TRACE_NAMESPACE: ""
  TRACE_OTEL_ENDPOINT: "tempo-distributor.observability:4318"
  TRACE_OTEL_URL_PATH: "/v1/traces"
  TRACE_OTEL_COMPRESSION: "false"
  TRACE_OTEL_INSECURE: "true"
  TRACE_OTEL_TIMEOUT: "10"
