---
apiVersion: v1
kind: Service
metadata:
  name: harbor-jobservice
spec:
  ports:
  - name: https-jobservice
    port: 443
    targetPort: 8443
  - name: https-metrics
    port: 8001
  selector:
    release: harbor
    app: harbor
    component: jobservice
