---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-data-pv
  labels:
    type: local
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  hostPath:
    path: /var/local/data/keycloak
  storageClassName: local-path
