---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tools

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: keycloak

resources:
- keycloak
- postgres

patches:
- path: patches/keycloak-env-cm.yaml

replacements:
- path: patches/keycloak-db-name.yaml
- path: patches/keycloak-db-password.yaml
- path: patches/keycloak-db-user.yaml
