---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-env-cm
  labels:
    app.kubernetes.io/name: forgejo-env-cm
    app.kubernetes.io/component: configuration
data:
  HOME: /var/lib/forgejo/git
  USER_UID: "1000"
  USER_GID: "1000"
  TMPDIR: /tmp/forgejo
  FORGEJO_APP_INI: /etc/forgejo/app.ini
  FORGEJO_CUSTOM: /var/lib/forgejo/custom
  FORGEJO_TEMP: /tmp/forgejo
  FORGEJO_WORK_DIR: /var/lib/forgejo
