---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo
  labels:
    app.kubernetes.io/name: forgejo
    app.kubernetes.io/instance: forgejo
    app.kubernetes.io/component: deployment
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: forgejo
      app.kubernetes.io/instance: forgejo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: forgejo
        app.kubernetes.io/instance: forgejo
    spec:
      terminationGracePeriodSeconds: 60
      initContainers:
      - name: init-directories
        image: codeberg.org/forgejo/forgejo:1.21-rootless
        imagePullPolicy: IfNotPresent
        command: ["/usr/local/sbin/init_directory_structure.sh"]
        envFrom:
        - configMapRef:
            name: forgejo-env-cm
        - secretRef:
            name: forgejo-env-secrets
        volumeMounts:
        - name: init-volume
          mountPath: /usr/local/sbin
        - name: temp-volume
          mountPath: /tmp/forgejo
        - name: config-volume
          mountPath: /etc/forgejo
        - name: data-volume
          mountPath: /var/lib/forgejo
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
      - name: init-app-ini
        image: codeberg.org/forgejo/forgejo:1.21-rootless
        imagePullPolicy: IfNotPresent
        command: ["/usr/local/sbin/config_environment.sh"]
        # # Do nothing so we can debug (troubleshooting-start) ->
        # command: [ "/bin/sh", "-c", "--" ]
        # args: [ "sleep 900; /usr/local/sbin/config_environment.sh;" ]
        # # <- (troubleshooting-end)
        envFrom:
        - configMapRef:
            name: forgejo-env-cm
        - secretRef:
            name: forgejo-env-secrets
        volumeMounts:
        - name: config-scripts-volume
          mountPath: /usr/local/sbin
        - name: temp-volume
          mountPath: /tmp/forgejo
        - name: config-volume
          mountPath: /etc/forgejo
        - name: data-volume
          mountPath: /var/lib/forgejo
        - name: inline-config-volume
          mountPath: /env-to-ini-mounts/inlines/
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
      - name: configure-forgejo
        image: codeberg.org/forgejo/forgejo:1.21-rootless
        command: ["/usr/local/sbin/configure_forgejo.sh"]
        # # Do nothing so we can debug (troubleshooting-start) ->
        # command: [ "/bin/sh", "-c", "--" ]
        # args: [ "sleep 600;" ]
        # # <- (troubleshooting-end)
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: forgejo-env-cm
        - secretRef:
            name: forgejo-env-secrets
        volumeMounts:
        - name: init-volume
          mountPath: /usr/local/sbin
        - name: temp-volume
          mountPath: /tmp/forgejo
        - name: config-volume
          mountPath: /etc/forgejo
        - name: data-volume
          mountPath: /var/lib/forgejo
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
      containers:
      - name: forgejo
        image: codeberg.org/forgejo/forgejo:1.21-rootless
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: forgejo-env-cm
        - secretRef:
            name: forgejo-env-secrets
        ports:
        - containerPort: 2222
          name: forgejo-ssh
          protocol: TCP
        - containerPort: 3000
          name: forgejo-http
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 64Mi
        livenessProbe:
          httpGet:
            path: /api/healthz
            port: http
          initialDelaySeconds: 200
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
        - name: temp-volume
          mountPath: /tmp/forgejo
        - name: config-volume
          mountPath: /etc/forgejo
        - name: data-volume
          mountPath: /var/lib/forgejo
      volumes:
      - name: init-volume
        secret:
          secretName: forgejo-init
          defaultMode: 110
      - name: config-scripts-volume
        secret:
          secretName: forgejo-config-scripts
          defaultMode: 110
      - name: inline-config-volume
        secret:
          secretName: forgejo-inline-config
      - name: temp-volume
        emptyDir: {}
      - name: config-volume
        persistentVolumeClaim:
          claimName: forgejo-config-pvc
      - name: data-volume
        persistentVolumeClaim:
          claimName: forgejo-data-pvc
