---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tools

labels:
- includeSelectors: true
  pairs:
    app: forgejo
    app.kubernetes.io/app: forgejo
    app.kubernetes.io/component: application

resources:
- configmap-env.yaml
- deployment.yaml
- ingress.yaml
- persistentvolumeclaim-config.yaml
- persistentvolumeclaim-data.yaml
- secret-config-scripts.yaml
- secret-env.yaml
- secret-init.yaml
- secret-inline-config.yaml
- service-web.yaml
- service-git-ssh.yaml
- servicemonitor.yaml
