---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tools

labels:
- includeSelectors: true
  pairs:
    app: forgejo
- includeSelectors: false
  pairs:
    app.kubernetes.io/version: 1.21.5
    version: 1.21.5

resources:
- configmap-env.yaml
- deployment.yaml
- ingress.yaml
- persistentvolumeclaim-config.yaml
- persistentvolumeclaim-data.yaml
- secret-config-scripts.yaml
- secret-env.yaml
- secret-init.yaml
- secret-inline-config.yaml
- service-web.yaml
- service-ssh.yaml
- servicemonitor.yaml
