---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-config-pvc
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
