---
exclude: |
  (?x)^(
      platform/ansible/installed/.*|
      kubernetes/apps/kubernetes-dashboard/dashboard\.yaml
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Git style
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: forbid-new-submodules
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: detect-private-key
      # Common errors
      - id: end-of-file-fixer
        exclude_types:
          - svg
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: CHANGELOG.md
      - id: check-executables-have-shebangs
      # Cross platform
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf]
      # Security
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      # Linters and Formatters
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix", "--no-sort-keys"]
  # - repo: https://github.com/jumanjihouse/pre-commit-hooks
  #   rev: 3.0.0
  #   hooks:
  #     - id: shfmt
  #       args: ["-l", "-i", "2", "-ci", "-sr", "-w"]
  #     - id: shellcheck
  # Markdown/CommonMark Linter
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        # Makefile Linter
  # Jsonnet Linter e Formatter
  - repo: https://github.com/google/go-jsonnet
    rev: v0.20.0
    hooks:
      - id: jsonnet-format
      - id: jsonnet-lint
        args: ["platform/vm-generator/virtual-machines.jsonnet", "--jpath", "platform/vm-generator/test"]
        pass_filenames: false
  # YAML Formatter
  - repo: https://github.com/google/yamlfmt
    rev: v0.11.0
    hooks:
      # Generic
      - id: yamlfmt
        name: Format generic YAML files (exclude kubernetes and ansible)
        alias: yamlfmt-generic
        args: [-conf, .yamlfmt]
        exclude: |
          (?x)^(
              kubernetes\/.*|
              platform\/ansible\/.*
          )$
      # Kubernetes
      - id: yamlfmt
        name: YAML format for kubernetes files
        alias: yamlfmt-k8s
        args: [-conf, kubernetes/.yamlfmt]
        files: ^kubernetes\/.*\.ya?ml$
      # Ansible
      - id: yamlfmt
        name: YAML format for ansible files
        alias: yamlfmt-ansible
        args: [-conf, platform/ansible/.yamlfmt]
        files: ^platform\/ansible\/.*\.ya?ml$
        exclude: ^platform\/ansible\/installed\/.*
