#!/usr/bin/env bash
set -Eeuo pipefail

project_name="iam-demo"
project_path=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

declare -a available_clusters=()
declare -a selected_clusters=()

while IFS='' read -r line; do available_clusters+=("$line"); done < \
  <(find clusters -type d -maxdepth 1 -mindepth 1 -exec basename {} \;)

__usage=$(
  cat <<-HELPMSG
		Usage: $(tput bold)$0 [OPTIONS]$(tput sgr0)

		Manage k8s clusters.

		Options:
		  -s, --setup                       Install requirements
		  -b, --bootstrap                   Create clusters
		  -p, --provision                   Provision clusters using the
		  -d, --delete                      Delete clusters
		  -c, --clusters $(tput setaf 3)<CL1> <...> <CLn>  $(tput sgr0)Limit clusters to selected
		    $(tput setaf 3)If clusters is not set, default to: $(tput sgr0)
		      $(tput setaf 6)$(tput bold)${available_clusters[*]}$(tput sgr0)
		  -h, --help                        This help
HELPMSG
)

usage() {
  echo -e "$__usage"
}

if [ $# -lt 1 ]; then
  usage
  exit 1
fi

check_dependency() {
  if ! [ -x "$(command -v "$1")" ]; then
    echo -e "$(tput setaf 2)Error: $(tput bold)$1$(tput sgr0)$(tput setaf 2) is not installed.$(tput sgr0)" >&2
    exit 1
  fi
}

project_certs_path=${project_path:?}/data/certs
ca_project_certs_path=${project_certs_path}/ca
ca_global_certs_path=$(mkcert -CAROOT)
domains_tls_path=${project_certs_path}/domains/${project_name}
ca_project_key=${ca_project_certs_path}/rootCA-key.pem
ca_project_cert=${ca_project_certs_path}/rootCA.pem
domains_tls_key=${domains_tls_path}/key.pem
domains_tls_crt=${domains_tls_path}/cert.pem
project_domain="${project_name}"'.test'

generate_local_certs() {
  echo "Project: ${project_name}"
  echo -e "CA Certs will be installed in path:\n  ${ca_global_certs_path}"
  echo -e "CA Certs will be copied in path:\n  ${project_certs_path}"
  echo "Creating self-signed CA certificates for TLS and installing them in the local trust stores"
  mkdir -p "${ca_project_certs_path}"
  mkdir -p "${domains_tls_path}"
  mkcert -install
  if ! [ -f "${ca_project_key}" ]; then
    echo "Copying CA certs from ${ca_global_certs_path} to ${ca_project_certs_path}"
    cp "${ca_global_certs_path}/rootCA-key.pem" "${ca_project_key}"
    cp "${ca_global_certs_path}/rootCA.pem" "${ca_project_cert}"
  fi
  if [ -f "${domains_tls_crt}" ]; then
    echo "Existing certificate for ${project_domain} ✅"
  else
    mkcert -key-file "${domains_tls_key}" \
      -cert-file "${domains_tls_crt}" \
      "${project_domain}" '*.'"${project_domain}"
    chmod -vR go-rwx "${domains_tls_path}"
  fi
}

vault_unseal() {
  declare -a vault_pods=()
  vault_data_path="${project_path}/data/vault"
  mkdir -p "${vault_data_path}"

  while IFS='' read -r line; do vault_pods+=("${line}"); done < \
    <(kubectl get pods -l app.kubernetes.io/name=vault,vault-initialized=false --no-headers -o custom-columns=":metadata.name")

  if [ ${#vault_pods[@]} -gt 0 ]; then
    echo "Initializing Vault"
    if [ -f "${vault_data_path}/cluster-keys.json" ]; then
      local vault_keys_bu
      vault_keys_bu="${vault_data_path}/cluster-keys.json.$(date +"%Y-%m-%d_%H-%M-%S")"
      echo "🔥 Backup existing Vault cluster-keys.json in: ${vault_keys_bu}"
      mv "${vault_data_path}/cluster-keys.json" "${vault_keys_bu}"
    fi
    kubectl exec vault-0 -- vault operator init -key-shares=1 -key-threshold=1 -format=json >"${vault_data_path}/cluster-keys.json"
    vault_unseal_key=$(jq -r ".unseal_keys_b64[]" "${vault_data_path}/cluster-keys.json")

    for vault_pod in "${vault_pods[@]}"; do
      kubectl exec "${vault_pod}" -- vault operator unseal "${vault_unseal_key}"
    done
  else
    echo "Vault is already initialized ✅"
  fi
}

create_cluster() {
  local cluster_name=$1
  local cluster_context="kind-${cluster_name}"
  local cmd_output
  local exit_status
  check_dependency 'kubectl'
  cmd_output=$(kubectl cluster-info --context "${cluster_context}" 2>&1) && exit_status=$? || exit_status=$?
  local check="error: context \"${cluster_context}\" does not exist"
  if [[ $cmd_output =~ $check ]]; then
    check_dependency kind
    echo -en "$(tput setaf 4)-- Creating clusters: $(tput bold)$cluster_name$(tput sgr0)$(tput setaf 4) using "
    echo -e "$(tput bold)Kind$(tput sgr0)"
    cluster_config_file="clusters_config/${cluster_name}/kind.yaml"
    if [ -f "$cluster_config_file" ]; then
      echo "✅ Using: $cluster_config_file"
      kind create cluster --wait 5m --config="$cluster_config_file" --name "$cluster_name"
    else
      kind create cluster --wait 5m --name "$cluster_name"
    fi
  elif [ "$exit_status" -ne "0" ]; then
    echo -e "$(tput setaf 1)kubectl error for $(tput bold)$cluster_name$(tput sgr0).\n" >&2
    echo -e "$(tput setaf 5)$cmd_output$(tput sgr0).\n" >&2
    exit 2
  else
    echo -e "$(tput setaf 3)Cluster $(tput setaf 6)$(tput bold)$cluster_name$(tput sgr0)$(tput setaf 3) already exist$(tput sgr0)"
  fi
}

project_setup_darwin() {
  # Install dependencies
  check_dependency 'brew'
  if ! hash envsubst >/dev/null 2>&1; then
    brew install gettext
  fi
  for cmd_name in jq yq docker kubectl kind helm mkcert; do
    if ! hash "${cmd_name}" >/dev/null 2>&1; then
      brew install "${cmd_name}"
    else
      echo "- ${cmd_name} ✅"
    fi
  done
  if brew list docker-mac-net-connect &>/dev/null; then
    echo "- docker-mac-net-connect ✅"
  else
    brew install chipmk/tap/docker-mac-net-connect
    # Run the service and register it to launch at boot
    brew services restart chipmk/tap/docker-mac-net-connect
  fi
}

clusters_bootstrap() {
  local clusters="$1[@]"
  local cluster
  echo -e "$(tput setaf 3)Bootsrapping Clusters: $(tput setaf 6)$(tput bold)${!clusters}$(tput sgr0)"
  for cluster in "${!clusters}"; do
    echo -e "$(tput setaf 3)Bootsrap: $(tput setaf 6)$(tput bold)${cluster}$(tput sgr0)"
    create_cluster "${cluster}"
    local cluster_context="kind-${cluster}"

    control_plane_ip=$(docker container inspect "${cluster}-control-plane" --format '{{ .NetworkSettings.Networks.kind.IPAddress }}')

    export control_plane_ip
    export project_domain

    echo "Control plane IP: '${control_plane_ip}'"

    sudo mkdir -p /etc/resolver
    envsubst <"${project_path}/clusters_config/resolver_project_domain.tmpl" | sudo tee "/etc/resolver/${project_domain}"

    sudo dscacheutil -flushcache
    sudo killall -HUP mDNSResponder

    kubectl get configmaps coredns --context "${cluster_context}" \
      -n kube-system -o yaml >"${project_path}/clusters/$cluster/pre-provision/coredns_configmap.yaml"

    corefile_data=$(envsubst <"${project_path}/clusters_config/$cluster/corefile.txt") \
      yq '.data.Corefile = strenv(corefile_data)' -i "${project_path}/clusters/$cluster/pre-provision/coredns_configmap.yaml"

    kubectl replace --context "${cluster_context}" -n kube-system \
      -f "${project_path}/clusters/$cluster/pre-provision/coredns_configmap.yaml"

    cluster_post_bootstrap "${cluster}"
  done
}

cluster_post_bootstrap() {
  local cluster_name=$1
  local cluster_context="kind-${cluster_name}"
  check_dependency 'kubectl'
  echo "$(tput setaf 3)Post Bootstrap $(tput setaf 6)$(tput bold)$cluster_name$(tput sgr0)"

  helm repo add jetstack https://charts.jetstack.io
  helm repo add hashicorp https://helm.releases.hashicorp.com
  helm repo add grafana https://grafana.github.io/helm-charts
  helm repo update

  echo "$(tput setaf 3)Installing $(tput setaf 6)$(tput bold)cert-manager$(tput sgr0)"
  helm upgrade --install cert-manager jetstack/cert-manager \
    --namespace cert-manager \
    --create-namespace \
    --set installCRDs=true \
    --wait --timeout=90s

  kubectl -n cert-manager create secret tls "${project_name}-ca" \
    --context "${cluster_context}" \
    --key "${ca_project_key}" \
    --cert "${ca_project_cert}" \
    --dry-run=client \
    -o yaml \
    | kubectl apply -f -

  kubectl -n cert-manager create secret tls "${project_name}-tls" \
    --context "${cluster_context}" \
    --key "${domains_tls_key}" \
    --cert "${domains_tls_crt}" \
    --dry-run=client \
    -o yaml \
    | kubectl apply -f -

  kubectl kustomize "clusters/${cluster_name}/pre-provision" --context "${cluster_context}" | kubectl apply -f -

  kubectl -n tools create secret tls "${project_name}-ca" \
    --context "${cluster_context}" \
    --key "${ca_project_key}" \
    --cert "${ca_project_cert}" \
    --dry-run=client \
    -o yaml \
    | kubectl apply -f -

  helm upgrade --install consul hashicorp/consul --create-namespace -n consul \
    --values "${project_path}/clusters_config/${cluster_name}/helm-consul-values.yml"
  helm upgrade --install vault hashicorp/vault \
    --values "${project_path}/clusters_config/${cluster_name}/helm-vault-values.yml"
  helm upgrade --install loki --namespace=monitoring grafana/loki
  helm upgrade --install grafana --namespace=monitoring grafana/grafana
}

cluster_provisioning() {
  local cluster_name=$1
  local cluster_context="kind-${cluster_name}"
  check_dependency 'kubectl'
  echo "$(tput setaf 3)Provisioning $(tput setaf 6)$(tput bold)$cluster_name$(tput sgr0)"

  vault_unseal

  kubectl kustomize "clusters/$cluster_name" --context "${cluster_context}" | kubectl apply -f -
  sleep 15
  kubectl wait --context "${cluster_context}" --namespace ingress-nginx \
    --for=condition=ready pod \
    --selector=app.kubernetes.io/component=controller \
    --timeout=90s
}

cluster_post_provisioning() {
  local cluster_name=$1
  local cluster_context="kind-${cluster_name}"
  check_dependency 'kubectl'
  echo "$(tput setaf 3)Post-Provisioning $(tput setaf 6)$(tput bold)$cluster_name$(tput sgr0)"
}

delete_cluster() {
  local cluster_name=$1
  kind delete cluster --name "$cluster_name"
}

array_contains_element() {
  local array="$1[@]"
  local seeking=$2
  local contained
  local element
  contained=false
  for element in "${!array}"; do
    if [[ $element == "$seeking" ]]; then
      contained=true
      break
    fi
  done
  $contained
}

chech_clusters() {
  local _selected_clusters="$1[@]"
  local _available_clusters="$2[@]"
  local element
  valid_clusters=true
  for element in "${!_selected_clusters}"; do
    if ! array_contains_element "$_available_clusters" "$element"; then
      echo -en "$(tput setaf 1)Cluster $(tput bold)$element$(tput sgr0)" >&2
      echo -e "$(tput setaf 1) not present in available clusters: $(tput bold)${!_available_clusters}$(tput sgr0)" >&2
      valid_clusters=false
    fi
  done
  $valid_clusters
}

clusters_provisioning() {
  local clusters="$1[@]"
  local cluster
  echo -e "$(tput setaf 3)Provisioning Clusters: $(tput setaf 6)$(tput bold)${!clusters}$(tput sgr0)"
  for cluster in "${!clusters}"; do
    cluster_provisioning "${cluster}"
    cluster_post_provisioning "${cluster}"
  done
}

clusters_delete() {
  local clusters="$1[@]"
  local cluster
  echo -e "$(tput setaf 3)Clusters to delete: $(tput setaf 6)$(tput bold)${!clusters}$(tput sgr0)"
  for cluster in "${!clusters}"; do
    delete_cluster "${cluster}"
  done
}

setup=false
bootstrap=false
provision=false
delete=false
all_available_clusters=true
while [ $# -gt 0 ] && [ "$1" != "" ]; do
  case $1 in
    -s | --setup)
      shift
      setup=true
      ;;
    -b | --bootstrap)
      shift
      bootstrap=true
      ;;
    -p | --provision)
      shift
      provision=true
      ;;
    -d | --delete)
      shift
      delete=true
      ;;
    -c | --clusters)
      shift
      if [ $# -lt 1 ] || [[ "${1::1}" == "-" ]]; then
        echo "$(tput setaf 1)Need a cluster name$(tput sgr0)" >&2
        printf "$(tput setaf 1)Available clusters: $(tput bold)%s$(tput sgr0)\n" "${available_clusters[*]}" >&2
        usage
        exit 1
      fi
      while [ $# -gt 0 ] && [ "$1" != "" ]; do
        if [[ "${1::1}" == "-" ]]; then
          break
        else
          all_available_clusters=false
          selected_clusters+=("$1")
          shift
        fi
      done
      ;;
    -h | --help)
      shift
      usage
      exit 0
      ;;
    *)
      printf "$(tput setaf 1)Unexpected argument: $(tput bold)%s$(tput sgr0)\n" "$1" >&2
      usage
      exit 1
      ;;
  esac
done

if $all_available_clusters; then
  selected_clusters=("${available_clusters[@]}")
else
  echo "Checking clusters $(tput bold)${selected_clusters[*]}$(tput sgr0)"
  if ! chech_clusters selected_clusters available_clusters; then
    usage
    exit 1
  fi
fi

printf "\nConfiguration:\n setup='%s'\n bootstrap='%s'\n provision='%s'\n delete='%s'\n" "${setup}" "${bootstrap}" "${provision}" "${delete}"
printf "\nSelected clusters: %s\n" ${selected_clusters[@]+"${selected_clusters[@]}"}

if $delete; then
  clusters_delete selected_clusters
  exit 0
fi

if $setup; then
  echo "$(tput bold)Setup$(tput sgr0)"
  case "$OSTYPE" in
    darwin*) project_setup_darwin ;;
    *)
      echo "Setup step not implemented for '$OSTYPE'"
      echo "Please install dependencies manually"
      ;;
  esac
  generate_local_certs
fi
if $bootstrap; then
  clusters_bootstrap selected_clusters
fi
if $provision; then
  clusters_provisioning selected_clusters
fi

exit 0
