#!/usr/bin/env bash
set -Eeuo pipefail

generator_orchestrator=multipass
host_architecture=$(uname -m)
instance_admin_password=ubuntu

project_path=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
generated_path=generated
project_generator_path="${project_path}/platform/instances-script-generator"
generated_project_path="${project_path}/${generated_path}"
valid_architectures=( amd64 x86_64 arm64 aarch64 )
valid_orchestrators=( fake multipass vbox )

__usage=$(
	cat <<-HELPMSG
		$(tput setaf 2)Usage:$(tput sgr0) $(tput bold)$0 [OPTIONS]$(tput sgr0)

		$(tput setaf 3)$(tput bold)Manage instances provisioning.$(tput sgr0)

		Options:
		  -a, --all                   $(tput setaf 8)Run all tasks to setup instances (in order: generate create setup provision)$(tput sgr0)
		  -o, --orchestrator          $(tput setaf 8)Select orchestrator for instances management scripts generator (default: '${generator_orchestrator}')$(tput sgr0)
		  -m, --machine-architecture  $(tput setaf 8)Host architecture (default: '${host_architecture}' using 'uname -m')$(tput sgr0)
		  -g, --generate              $(tput setaf 8)Generate instances management scripts$(tput sgr0)
		  -c, --create                $(tput setaf 8)Create instances using generated scripts$(tput sgr0)
		  -s, --setup                 $(tput setaf 8)Setup instances using generated scripts$(tput sgr0)
		  -p, --provision             $(tput setaf 8)Provision instances using generated scripts$(tput sgr0)
		  -d, --delete                $(tput setaf 8)Delete instances and local project data using generated scripts$(tput sgr0)
		  -h, --help                  $(tput setaf 8)This help$(tput sgr0)
	HELPMSG
)

usage() {
  echo -e "$__usage"
}

if [ $# -lt 1 ]; then
  usage
  exit 1
fi

check_dependency() {
  if ! [ -x "$(command -v "$1")" ]; then
    echo -e "$(tput setaf 2)Error: $(tput bold)$1$(tput sgr0)$(tput setaf 2) is not installed.$(tput sgr0)" >&2
    exit 1
  fi
}

generate_ansible_ssh_keys() {
  if [ -f "${generated_project_path}/assets/.ssh/id_ed25519.pub" ]; then
    echo "Using existing SSH keys for ansible ✅"
  else
    check_dependency 'ssh-keygen'
    echo "Generating SSH keys for ansible ..."
    mkdir -p "${generated_project_path}/assets/.ssh"
    ssh-keygen -t ed25519 -C "automator@iam-demo.test" -f "${generated_project_path}/assets/.ssh/id_ed25519" -q -N ""
  fi
}

generate_bootstrap_scripts() {
  check_dependency 'jsonnet'
  if [ -f "${project_generator_path}/config/config.libsonnet" ]; then
    echo "Using existing $(tput bold)config.libsonnet$(tput sgr0) ✅"
  else
    echo "Missing config.libsonnet"
    echo "Copying config.libsonnet.${generator_orchestrator}.example to config.libsonnet"
    cp "${project_generator_path}/config/config.libsonnet.${generator_orchestrator}.example" "${project_generator_path}/config/config.libsonnet"
  fi
  if [ -f "${generated_project_path}/assets/admin_password" ]; then
    echo "Using existing password from $(tput bold)${generated_project_path}/assets/admin_password$(tput sgr0) ✅"
  else
    echo "Generating password in $(tput bold)${generated_project_path}/assets/admin_password$(tput sgr0)"
    openssl passwd -6 -salt $(openssl rand -base64 8) "${instance_admin_password}" > "${generated_project_path}/assets/admin_password"
  fi
  echo "Using orchestrator: $(tput bold)${generator_orchestrator}$(tput sgr0)"
  echo "Using host_architecture: $(tput bold)${host_architecture}$(tput sgr0)"
  # cd "${project_generator_path}"
  jsonnet --create-output-dirs \
    --multi "${generated_project_path}" \
    --ext-str project_path="${project_path}" \
    --ext-str orchestrator_name="${generator_orchestrator}" \
    --ext-str host_architecture="${host_architecture}" \
    --jpath "${project_path}" \
    --jpath "${project_generator_path}" \
    --jpath "${project_generator_path}/config" \
    --string "${project_generator_path}/instances.jsonnet"
  chmod u+x "${generated_project_path}"/*.sh
}

instances_creations() {
  cd "${generated_project_path}"
  ./instances-create.sh
}

instances_setup() {
  cd "${generated_project_path}"
  ./instances-setup.sh
}

instances_provisioning() {
  cd "${generated_project_path}"
  ./instances-provisioning.sh
}

instances_delete() {
  cd "${generated_project_path}"
  ./instances-destroy.sh
}

create=false
generate=false
provision=false
setup=false
delete=false
while [ $# -gt 0 ] && [ "$1" != "" ]; do
  case $1 in
    -a | --all)
      shift
      generate=true
      create=true
      setup=true
      provision=true
      ;;
    -o | --orchestrator)
      generator_orchestrator=( "${2?Missing argument for  -o | --orchestrator}" ) ;
      shift
      shift
      ;;
    -m | --machine-architecture)
      host_architecture=( "${2?Missing argument for  -m | --machine-architecture}" ) ;
      shift
      shift
      ;;
    -g | --generate)
      shift
      generate=true
      ;;
    -c | --create)
      shift
      create=true
      ;;
    -s | --setup)
      shift
      setup=true
      ;;
    -p | --provision)
      shift
      provision=true
      ;;
    -d | --delete)
      shift
      delete=true
      ;;
    -h | --help)
      shift
      usage
      exit 0
      ;;
    *)
      printf "$(tput setaf 1)Unexpected argument: $(tput bold)%s$(tput sgr0)\n" "$1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ ! " ${valid_architectures[*]} " =~ " ${host_architecture} " ]]; then
  printf "$(tput setaf 1)Error: 'host_architecture' must be one of: $(tput bold)${valid_architectures[*]}$(tput sgr0)\n" >&2
  exit 1
fi

if [[ ! " ${valid_orchestrators[*]} " =~ " ${generator_orchestrator} " ]]; then
  printf "$(tput setaf 1)Error: 'orchestrator' must be one of: $(tput bold)${valid_orchestrators[*]}$(tput sgr0)\n" >&2
  exit 1
fi

if $delete; then
  instances_delete
  exit 0
fi

if $generate; then
  echo "$(tput bold)$(tput setaf 2) - Creating instances setup scripts ... - $(tput sgr0)"
  generate_ansible_ssh_keys
  generate_bootstrap_scripts
  echo "$(tput bold)$(tput setaf 2) - Instances setup scripts generated ✅ - $(tput sgr0)"
fi
if $create; then
  echo "$(tput bold)$(tput setaf 2) - Starting instances creation ... - $(tput sgr0)"
  instances_creations
  echo "$(tput bold)$(tput setaf 2) - Instances creation done ✅ - $(tput sgr0)"
fi
if $setup; then
  echo "$(tput bold)$(tput setaf 2) - Running instances setup ... - $(tput sgr0)"
  instances_setup
  echo "$(tput bold)$(tput setaf 2) - Instances setup done ✅ - $(tput sgr0)"
fi
if $provision; then
  echo "$(tput bold)$(tput setaf 2) - Starting instances provisioning ... - $(tput sgr0)"
  instances_provisioning
  echo "$(tput bold)$(tput setaf 2) - Instances provisioning done ✅ - $(tput sgr0)"
fi

echo "$(tput bold)$(tput setaf 2) - All done ✅ - $(tput sgr0)"
echo
echo "$(tput setaf 3)Project path: $(tput bold)${project_path}$(tput sgr0)"

if $create || $setup || $provision; then
  echo
  echo "$(tput setaf 3)To ssh into an instance use $(tput bold)./instance-shell.sh <instance-name>$(tput sgr0) from the generated folder."
  echo "  $(tput bold)$(tput setaf 5)Example:$(tput sgr0)"
  echo "  $(tput bold)cd ${generated_project_path}$(tput sgr0)"
  echo "  $(tput bold)./instance-shell.sh ansible-controller$(tput sgr0)"
fi
