---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: harbor
spec:
  jobLabel: app.kubernetes.io/name
  endpoints:
  - port: https-metrics
    honorLabels: true
    metricRelabelings:
    - action: keep
      regex: kube_(daemonset|deployment|pod|namespace|node|statefulset).+
      sourceLabels:
      - __name__
    relabelings:
    - action: replace
      regex: ^(.*)$
      replacement: $1
      separator: ;
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: nodename
  selector:
    matchLabels:
      release: harbor
      app: harbor
