---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: terrakube-dex-cluster
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: terrakube-dex
subjects:
- kind: ServiceAccount
  name: terrakube-dex
