---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: dex
    app.kubernetes.io/instance: terrakube

resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- role.yaml
- rolebinding.yaml
- secrets.yaml
- secrets-gcp.yaml
- service.yaml
- serviceaccount.yaml

secretGenerator:
- name: terrakube-dex-secrets
  behavior: merge
  files:
  - config.yaml=dex-config.yaml
