---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/app: dex
    app.kubernetes.io/name: terrakube-dex
    app.kubernetes.io/component: OIDC

resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- role.yaml
- rolebinding.yaml
- secrets.yaml
- secrets-files.yaml
- secrets-gcp.yaml
- service.yaml
- serviceaccount.yaml

secretGenerator:
- name: terrakube-dex-files-secrets
  behavior: merge
  files:
  - config.yaml=assets/config.yaml
