---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: terrakube-dex
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: terrakube-dex
subjects:
- kind: ServiceAccount
  name: terrakube-dex
