---
apiVersion: v1
kind: Service
metadata:
  name: terrakube-dex-svc
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: dex
  ports:
  - name: http
    port: 5556
    targetPort: http
    protocol: TCP
    appProtocol: http
  - name: telemetry
    port: 5558
    targetPort: telemetry
    protocol: TCP
    appProtocol: http
