---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
      - name: openldap
        image: bitnami/openldap:2.6
        env:
        - name: LDAP_CUSTOM_LDIF_DIR
          value: "/ldifs"
        envFrom:
        - configMapRef:
            name: openldap-env-cm
        - secretRef:
            name: openldap-env-secrets
        ports:
        - containerPort: 1389
        volumeMounts:
        - name: openldap-config
          mountPath: "/ldifs/config-ldap.ldif"
          subPath: "config-ldap.ldif"
          readOnly: true
      volumes:
      - name: openldap-config
        secret:
          secretName: openldap-files-secrets
          items:
          - key: "config-ldap.ldif"
            path: "config-ldap.ldif"
