---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: openldap
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: openldap
    spec:
      containers:
      - name: openldap
        image: bitnami/openldap:2.6
        env:
        - name: LDAP_CUSTOM_LDIF_DIR
          value: "/var/local/ldifs"
        envFrom:
        - configMapRef:
            name: openldap-env-cm
        - secretRef:
            name: openldap-env-secrets
        ports:
        - containerPort: 1389
        volumeMounts:
        - name: openldap-config
          mountPath: /var/local/ldifs
          readOnly: true
      volumes:
      - name: openldap-config
        secret:
          secretName: openldap-ldif-files-secrets
