---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app: openldap
    app.kubernetes.io/component: ldap
    role: data

resources:
- deployment.yaml
- secret.yaml
- service.yaml

secretGenerator:
- name: openldap-secrets
  behavior: merge
  files:
  - config-ldap.ldif
