---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app: openldap
    app.kubernetes.io/component: ldap
    role: data

resources:
- configmap.yaml
- deployment.yaml
- secrets.yaml
- service.yaml

secretGenerator:
- name: openldap-files-secrets
  files:
  - config-ldap.ldif=assets/config-ldap.ldif
