---
apiVersion: v1
kind: Service
metadata:
  name: openldap-svc
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: openldap
  ports:
  - name: openldap-port
    port: 1389
    targetPort: 1389
