---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app: terrakube-ui
    app.kubernetes.io/app: terrakube-ui
    app.kubernetes.io/component: ui

resources:
- deployment.yaml
- ingress.yaml
- secrets.yaml
- service.yaml
