---
apiVersion: v1
kind: Secret
metadata:
  name: terrakube-ui-secrets
type: Opaque
stringData:
  # This UI configuration file is loaded in /app/env-config.js
  env-config.js: |
    window._env_ = {
      REACT_APP_TERRAKUBE_API_URL: "https://terrakube-api.iam-demo.test/api/v1/",
      REACT_APP_CLIENT_ID: "iamdemo-app",
      REACT_APP_AUTHORITY: "https://terrakube-api.iam-demo.test/dex",
      REACT_APP_REDIRECT_URI: "https://terrakube-ui.iam-demo.test",
      REACT_APP_REGISTRY_URI: "https://terrakube-reg.iam-demo.test",
      REACT_APP_SCOPE: "email openid profile offline_access groups",
      REACT_APP_TERRAKUBE_VERSION: "2.24.1",
    }
