---
# To generate reference values, run:
#   helm show values grafana/loki
#
# NOTE: This helm chart currently use Hard node anti-affinity and cannot be changed.
#
# We use this config file only to generate files for kustomize

loki:
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
    - from: "2025-01-01"
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h
  ingester:
    chunk_encoding: snappy
  tracing:
    enabled: true
  querier:
    max_concurrent: 2
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    volume_max_series: 1000
  ruler:
    enable_api: true
  auth_enabled: false
  storage:
    type: s3
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    s3:
      endpoint: "${MINIO_S3_ENDPOINT}"
      accessKeyId: "${MINIO_S3_ACCESKEYID}"
      secretAccessKey: "${MINIO_S3_SECRETACCESSKEY}"
      insecure: true
      s3ForcePathStyle: true

# We use an external MinIO
minio:
  enabled: false

deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  extraArgs:
  - '-config.expand-env=true'
  extraEnv:
  - name: MINIO_S3_ENDPOINT
    valueFrom:
      configMapKeyRef:
        name: minio-url
        key: internalEndpoint
  - name: MINIO_S3_ACCESKEYID
    valueFrom:
      secretKeyRef:
        name: loki-s3-credentials
        key: user
  - name: MINIO_S3_SECRETACCESSKEY
    valueFrom:
      secretKeyRef:
        name: loki-s3-credentials
        key: password

# chunksCache:
#   allocatedMemory: 256
#   writebackSizeLimit: 10MB

# resultsCache:
#   allocatedMemory: 256
#   writebackSizeLimit: 10MB

resultsCache:
  enabled: false
chunksCache:
  enabled: false

gateway:
  enabled: true
  replicas: 1
  ingress:
    enabled: true
    labels:
      traffic: external
    annotations:
      cert-manager.io/cluster-issuer: iam-demo-certs-issuer
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
    - host: loki.iam-demo.test
      paths:
      - pathType: Prefix
        path: /
    tls:
    - secretName: iam-demo-loki-tls
      hosts:
      - loki.iam-demo.test

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
