---
global:
  enabled: true
  name: consul
  logLevel: info
  logJSON: true
  domain: consul
  image: hashicorp/consul:1.20
  imageK8S: hashicorp/consul-k8s-control-plane:1.6
  datacenter: iam-demo-dc
  peering:
    enabled: false

  tls:
    enabled: false

  acls:
    manageSystemACLs: false
    createReplicationToken: false

  argocd:
    enabled: false

  # Configure federation.
  federation:
    enabled: false

  metrics:
    enabled: true
    enableAgentMetrics: true
    enableHostMetrics: true
    enableTelemetryCollector: true

  imageConsulDataplane: hashicorp/consul-dataplane:1.6

server:
  enabled: true
  replicas: 1
  ports:
    serflan:
      port: 8301
  storage: 10Gi
  connect: true
  enableAgentDebug: false
  disruptionBudget:
    enabled: true
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: {{ template "consul.name" . }}
              release: "{{ .Release.Name }}"
              component: server
          topologyKey: kubernetes.io/hostname
  exposeService:
    enabled: "-"
    type: LoadBalancer

client:
  enabled: true

ui:
  enabled: true
  service:
    enabled: true
  ingress:
    enabled: true
    annotations: |
      cert-manager.io/cluster-issuer: iam-demo-certs-issuer
    hosts:
    - host: consul.iam-demo.test
      path: /
    tls:
    - hosts:
      - consul.iam-demo.test
      secretName: iam-demo-consul-tls
  metrics:
    enabled: true
    provider: prometheus
    baseURL: http://prometheus-observability-s-prometheus.observability:9090

syncCatalog:
  enabled: true
  default: true
  toConsul: true
  toK8S: true
  consulNamespaces:
    mirroringK8S: true
  syncClusterIPServices: true

connectInject:
  enabled: true
  replicas: 1
  default: false
  transparentProxy:
    defaultEnabled: true
    defaultOverwriteProbes: true
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
  apiGateway:
    manageExternalCRDs: true
    manageNonStandardCRDs: false
    managedGatewayClass:
      serviceType: LoadBalancer

telemetryCollector:
  enabled: true
  image: "hashicorp/consul-telemetry-collector:0.0.2"
  replicas: 1
