---
# We limit namespaces targets until the "Reconciler error"
# is fixed in trivy-operator.
targetNamespaces: "kube-system,security"
service:
  headless: false
  labels:
serviceMonitor:
  enabled: true
  labels:
    release: prometheus
trivy:
  ignoreUnfixed: true
  severity: HIGH,CRITICAL
trivyOperator:
  scanJobCompressLogs: false
operator:
  infraAssessmentScannerEnabled: false
  scanJobsConcurrentLimit: 3
  scanJobsRetryDelay: 90s
