---
global:
  enabled: true
  name: consul
  logLevel: info
  logJSON: true
  domain: consul
  image: hashicorp/consul:1.17.3
  imageK8S: hashicorp/consul-k8s-control-plane:1.3.3
  datacenter: iam-demo-dc
  metrics:
    enabled: true
    enableAgentMetrics: true
    enableHostMetrics: true
    enableTelemetryCollector: true
  imageConsulDataplane: hashicorp/consul-dataplane:1.3.3
  extraLabels:
    app.kubernetes.io/part-of: consul

server:
  enabled: true
  replicas: 1
  ports:
    serflan:
      port: 8301
  connect: true
  enableAgentDebug: false
  disruptionBudget:
    enabled: true

client:
  enabled: true

ui:
  enabled: true
  service:
    enabled: true
  ingress:
    enabled: true
    annotations: |
      cert-manager.io/cluster-issuer: iam-demo-certs-issuer
    hosts:
    - host: consul.iam-demo.test
      path: /
    tls:
    - hosts:
      - consul.iam-demo.test
      secretName: iam-demo-consul-tls
  metrics:
    enabled: true
    provider: prometheus
    baseURL: http://prometheus-observability-s-prometheus.observability:9090

syncCatalog:
  enabled: true
  toConsul: true
  toK8S: true
  consulNamespaces:
    mirroringK8S: true
  syncClusterIPServices: true

connectInject:
  enabled: true
  default: false
  transparentProxy:
    defaultEnabled: true
    defaultOverwriteProbes: true
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
  apiGateway:
    manageExternalCRDs: true
    manageNonStandardCRDs: false
    managedGatewayClass:
      serviceType: LoadBalancer

# only useful when running helm template.
tests:
  enabled: true

telemetryCollector:
  enabled: true
  image: "hashicorp/consul-telemetry-collector:0.0.2"
