---
# To generate reference values, run:
#   helm show values grafana/loki
#
# NOTE: This helm chart currently use Hard node anti-affinity and cannot be changed.
#
# We use this config file only to generate files for kustomize

loki:
  schemaConfig:
    configs:
    - from: "2024-04-01"
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: loki_index_
        period: 24h
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
  ruler:
    enable_api: true
  auth_enabled: false
  storage:
    type: s3
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    s3:
      endpoint: "${MINIO_S3_ENDPOINT}"
      accessKeyId: "${MINIO_S3_ACCESKEYID}"
      secretAccessKey: "${MINIO_S3_SECRETACCESSKEY}"
      insecure: true
      s3forcepathstyle: true

# We use an external MinIO
minio:
  enabled: false

chunksCache:
  enabled: false

gateway:
  enabled: true
  replicas: 1
  ingress:
    enabled: true
    labels:
      traffic: external
    annotations:
      cert-manager.io/cluster-issuer: iam-demo-certs-issuer
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
    - host: loki.iam-demo.test
      paths:
      - pathType: Prefix
        path: /
    tls:
    - secretName: iam-demo-loki-tls
      hosts:
      - loki.iam-demo.test

write:
  replicas: 3
  extraArgs:
  - '-config.expand-env=true'
  extraEnv:
  - name: MINIO_S3_ENDPOINT
    valueFrom:
      configMapKeyRef:
        name: minio-url
        key: internalEndpoint
  - name: MINIO_S3_ACCESKEYID
    valueFrom:
      secretKeyRef:
        name: loki-s3-credentials
        key: user
  - name: MINIO_S3_SECRETACCESSKEY
    valueFrom:
      secretKeyRef:
        name: loki-s3-credentials
        key: password

read:
  replicas: 3
  extraArgs:
  - '-config.expand-env=true'
  extraEnv:
  - name: MINIO_S3_ENDPOINT
    valueFrom:
      configMapKeyRef:
        name: minio-url
        key: internalEndpoint
  - name: MINIO_S3_ACCESKEYID
    valueFrom:
      secretKeyRef:
        name: loki-s3-credentials
        key: user
  - name: MINIO_S3_SECRETACCESSKEY
    valueFrom:
      secretKeyRef:
        name: loki-s3-credentials
        key: password

backend:
  replicas: 3
  extraArgs:
  - '-config.expand-env=true'
  extraEnv:
  - name: MINIO_S3_ENDPOINT
    valueFrom:
      configMapKeyRef:
        name: minio-url
        key: internalEndpoint
  - name: MINIO_S3_ACCESKEYID
    valueFrom:
      secretKeyRef:
        name: loki-s3-credentials
        key: user
  - name: MINIO_S3_SECRETACCESSKEY
    valueFrom:
      secretKeyRef:
        name: loki-s3-credentials
        key: password

lokiCanary:
  enabled: true

serviceAccount:
  create: true
