nameOverride: grafana-stack
namespaceOverride: monitoring

commonLabels:
  app.kubernetes.io/component: monitoring
  app.kubernetes.io/part-of: grafana-stack

alertmanager:
  enabled: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: iam-demo-certs-issuer
    labels:
      app.kubernetes.io/name: alertmanager
    hosts:
    - alertmanager.iam-demo.test
    paths:
    - /
    pathType: Prefix
    tls:
    - secretName: iam-demo-alertmanager-tls
      hosts:
      - alertmanager.iam-demo.test

grafana:
  enabled: true
  adminPassword: iam-demo-operator
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: iam-demo-certs-issuer
    labels:
      app.kubernetes.io/name: grafana
    hosts:
    - grafana.iam-demo.test
    paths:
    - /
    pathType: Prefix
    tls:
    - secretName: iam-demo-grafana-tls
      hosts:
      - grafana.iam-demo.test

prometheus:
  enabled: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: iam-demo-certs-issuer
    labels:
      app.kubernetes.io/name: prometheus
    hosts:
    - prometheus.iam-demo.test
    paths:
    - /
    pathType: Prefix
    tls:
    - secretName: iam-demo-prometheus-tls
      hosts:
      - prometheus.iam-demo.test
