---
agent:
  mode: 'flow'
  enableReporting: false
  configMap:
    create: false
    name: grafana-agent-flow-config
    key: config.river
  envFrom:
  - configMapRef:
      name: grafana-agent-flow-env
  # - secretRef:
  #     name: grafana-agent-flow-env-secrets
