---
# To generate reference values, run:
#   helm show values prometheus-community/kube-prometheus-stack
# or see:
# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

# nameOverride: observability-stack
fullnameOverride: o11y-stack

namespaceOverride: observability

commonLabels:
  app.kubernetes.io/component: monitoring
  app.kubernetes.io/part-of: observability

alertmanager:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: iam-demo-certs-issuer
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    labels:
      app.kubernetes.io/name: alertmanager
    hosts:
    - alertmanager.iam-demo.test
    paths:
    - /
    pathType: Prefix
    tls:
    - secretName: iam-demo-alertmanager-tls
      hosts:
      - alertmanager.iam-demo.test

grafana:
  enabled: true
  adminPassword: grafana-admin
  additionalDataSources:
  - name: Loki
    type: loki
    url: http://loki-gateway
    editable: true
    jsonData:
      maxLines: 1000
  # # Send logs to file
  # env:
  #   GF_LOG_MODE: console file
  #   GF_PATHS_LOGS: /var/log/grafana/
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: iam-demo-certs-issuer
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    labels:
      app.kubernetes.io/name: grafana
    hosts:
    - grafana.iam-demo.test
    paths:
    - /
    pathType: Prefix
    tls:
    - secretName: iam-demo-grafana-tls
      hosts:
      - grafana.iam-demo.test
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
      label: grafana_dashboard
      labelValue: '1'
    datasources:
      enabled: true
      searchNamespace: ALL
      label: grafana_datasource
      labelValue: '1'

prometheus:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: iam-demo-certs-issuer
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    labels:
      app.kubernetes.io/name: prometheus
    hosts:
    - prometheus.iam-demo.test
    paths:
    - /
    pathType: Prefix
    tls:
    - secretName: iam-demo-prometheus-tls
      hosts:
      - prometheus.iam-demo.test
  monitor:
    relabelings:
    - action: replace
      replacement: loki
      targetLabel: cluster

cleanPrometheusOperatorObjectNames: true

kubelet:
  serviceMonitor:
    cAdvisorRelabelings:
    - action: replace
      replacement: loki
      targetLabel: cluster
    - targetLabel: metrics_path
      sourceLabels:
      - __metrics_path__
    - targetLabel: instance
      sourceLabels:
      - node

defaultRules:
  additionalRuleLabels:
    cluster: loki

kube-state-metrics:
  prometheus:
    monitor:
    relabelings:
      - action: replace
        replacement: loki
        targetLabel: cluster
      - targetLabel: instance
        sourceLabels:
        - __meta_kubernetes_pod_node_name

prometheus-node-exporter:
  prometheus:
    monitor:
      relabelings:
      - action: replace
        replacement: loki
        targetLabel: cluster
      - targetLabel: instance
        sourceLabels:
        - __meta_kubernetes_pod_node_name
