---
apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-core
data:
  app.conf: |
    appname = Harbor
    runmode = prod
    enablegzip = true

    [prod]
    httpport = 8443
  PORT: "8443"
  DATABASE_TYPE: "postgresql"
  POSTGRESQL_HOST: "harbor-postgres"
  POSTGRESQL_PORT: "5432"
  POSTGRESQL_USERNAME: "postgres"
  POSTGRESQL_DATABASE: "registry"
  POSTGRESQL_SSLMODE: "disable"
  POSTGRESQL_MAX_IDLE_CONNS: "100"
  POSTGRESQL_MAX_OPEN_CONNS: "900"
  EXT_ENDPOINT: "https://harbor.iam-demo.test"
  CORE_URL: "https://harbor-core:443"
  JOBSERVICE_URL: "https://harbor-jobservice"
  REGISTRY_URL: "https://harbor-registry:5443"
  TOKEN_SERVICE_URL: "https://harbor-core:443/service/token"
  CORE_LOCAL_URL: "https://127.0.0.1:8443"
  WITH_TRIVY: "true"
  TRIVY_ADAPTER_URL: "https://harbor-trivy:8443"
  REGISTRY_STORAGE_PROVIDER_NAME: "filesystem"
  LOG_LEVEL: "info"
  CONFIG_PATH: "/etc/core/app.conf"
  CHART_CACHE_DRIVER: "redis"
  _REDIS_URL_CORE: "redis://harbor-redis:6379/0?idle_timeout_seconds=30"
  _REDIS_URL_REG: "redis://harbor-redis:6379/2?idle_timeout_seconds=30"
  PORTAL_URL: "https://harbor-portal"
  REGISTRY_CONTROLLER_URL: "https://harbor-registry:8443"
  REGISTRY_CREDENTIAL_USERNAME: "harbor_registry_user"
  HTTP_PROXY: ""
  HTTPS_PROXY: ""
  NO_PROXY: "harbor-core,harbor-jobservice,harbor-database,harbor-registry,harbor-portal,harbor-trivy,harbor-exporter,127.0.0.1,localhost,.local,.internal"
  PERMITTED_REGISTRY_TYPES_FOR_PROXY_CACHE: "docker-hub,harbor,azure-acr,aws-ecr,google-gcr,quay,docker-registry,github-ghcr,jfrog-artifactory"
  METRIC_ENABLE: "true"
  METRIC_PATH: "/metrics"
  METRIC_PORT: "8001"
  METRIC_NAMESPACE: harbor
  METRIC_SUBSYSTEM: core
  TRACE_SERVICE_NAME: "harbor-core"
  TRACE_ENABLED: "true"
  TRACE_SAMPLE_RATE: "1"
  TRACE_NAMESPACE: ""
  TRACE_OTEL_ENDPOINT: "tempo-distributor.observability:4318"
  TRACE_OTEL_URL_PATH: "/v1/traces"
  TRACE_OTEL_COMPRESSION: "false"
  TRACE_OTEL_INSECURE: "true"
  TRACE_OTEL_TIMEOUT: "10"
  QUOTA_UPDATE_PROVIDER: "db"
