---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    component: core
    app.kubernetes.io/name: harbor-core
resources:
- configmap.yaml
- deployment.yaml
- internal-tls.yaml
- secret.yaml
- service.yaml
