---
# Source: harbor/templates/core/core-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: harbor-core
spec:
  ports:
  - name: https-web
    port: 443
    targetPort: 8443
  - name: https-metrics
    port: 8001
  selector:
    release: harbor
    app: harbor
    component: core
