---
- name: Ensure target host architecture information is set as a fact
  check_mode: false
  ansible.builtin.set_fact:
    k3s_arch: "{{ k3s_arch_lookup[ansible_architecture].arch }}"
    k3s_arch_suffix: "{{ k3s_arch_lookup[ansible_architecture].suffix }}"
- name: Ensure URLs are set as facts for downloading binaries
  check_mode: false
  ansible.builtin.set_fact:
    k3s_binary_url: "{{ k3s_github_download_url }}/{{ k3s_release_version }}/k3s{{ k3s_arch_suffix }}"
    k3s_hash_url: "{{ k3s_github_download_url }}/{{ k3s_release_version }}/sha256sum-{{ k3s_arch }}.txt"
- name: Ensure the k3s hashsum is downloaded
  register: k3s_hash_sum_raw
  check_mode: false
  ansible.builtin.uri:
    url: "{{ k3s_hash_url }}"
    return_content: true
- name: Ensure sha256sum is set from hashsum variable
  changed_when: false
  check_mode: false
  ansible.builtin.set_fact:
    k3s_hash_sum: "{{ (k3s_hash_sum_raw.content.split('\n') |
      select('search', 'k3s' + k3s_arch_suffix) |
      reject('search', 'images') |
      first).split() | first }}"
- name: Ensure installation directory exists
  ansible.builtin.file:
    path: "{{ k3s_install_dir }}"
    state: directory
    mode: "u=rwx,g=rx,o=rx"
- name: Ensure k3s binary is downloaded
  become: "{{ k3s_become }}"
  ansible.builtin.get_url:
    url: "{{ k3s_binary_url }}"
    dest: "{{ k3s_install_dir }}/k3s-{{ k3s_release_version }}"
    checksum: "sha256:{{ k3s_hash_sum }}"
    mode: "u=rwx,g=rx,o=rx"
