---
- name: Ensure k3s_build_cluster is false if running against a single node.
  when:
    - ansible_play_hosts | length < 2
    - k3s_registration_address is not defined
  ansible.builtin.set_fact:
    k3s_build_cluster: false
- name: Ensure k3s control node fact is set
  when: k3s_control_node is not defined
  ansible.builtin.set_fact:
    k3s_control_node: "{{ not k3s_build_cluster }}"
- name: Ensure k3s primary control node fact is set
  when: k3s_primary_control_node is not defined
  ansible.builtin.set_fact:
    k3s_primary_control_node: "{{ not k3s_build_cluster }}"
- name: Ensure k3s control plane port is captured
  delegate_to: k3s_primary_control_node
  ansible.builtin.set_fact:
    k3s_control_plane_port: "{{ k3s_runtime_config['https-listen-port'] | default(6443) }}"
- name: Ensure k3s node IP is configured when node-ip is defined
  when:
    - k3s_runtime_config['node-ip'] is defined
  ansible.builtin.set_fact:
    k3s_node_ip: "{{ k3s_runtime_config['node-ip'] }}"
- name: Ensure a count of control nodes is generated from ansible_play_hosts
  when:
    - hostvars[item].k3s_control_node is defined
    - hostvars[item].k3s_control_node
  ansible.builtin.set_fact:
    k3s_controller_list: "{{ k3s_controller_list + [item] }}"
  loop: "{{ ansible_play_hosts }}"
- name: Ensure a k3s control node is defined if none are found in ansible_play_hosts
  when:
    - k3s_controller_list | length < 1
    - k3s_build_cluster is defined
    - k3s_build_cluster
  block:
    - name: Set the control host
      ansible.builtin.set_fact:
        k3s_control_node: true
      when: inventory_hostname == ansible_play_hosts[0]
    - name: Ensure a count of control nodes is generated
      ansible.builtin.set_fact:
        k3s_controller_list: "{{ k3s_controller_list + [item] }}"
      when:
        - hostvars[item].k3s_control_node is defined
        - hostvars[item].k3s_control_node
      loop: "{{ ansible_play_hosts }}"
- name: Ensure a primary k3s control node is defined if multiple are found in ansible_play_hosts
  when:
    - k3s_controller_list is defined
    - inventory_hostname == k3s_controller_list[0]
    - k3s_build_cluster is defined
    - k3s_build_cluster
  ansible.builtin.set_fact:
    k3s_primary_control_node: true
- name: Ensure ansible_host is mapped to inventory_hostname
  when: k3s_control_node is defined
  check_mode: false
  ansible.builtin.blockinfile:
    path: /tmp/inventory.txt
    create: true
    mode: u=rw,g=,o=
    block: |
      {% for host in ansible_play_hosts %}
      {% filter replace('\n', ' ') %}
      {{ host }}
      @@@
      {{ hostvars[host].ansible_host | default(hostvars[host].ansible_fqdn) | string }}
      @@@
      C_{{ hostvars[host].k3s_control_node | string }}
      @@@
      P_{{ hostvars[host].k3s_primary_control_node | default(False) | string }}
      {% endfilter %}
      @@@ END:{{ host }}
      {% endfor %}
- name: Delegate an initializing control plane node
  when: k3s_registration_address is not defined or k3s_control_delegate is not defined
  block:
    - name: Lookup control node from file
      changed_when: false
      check_mode: false
      ansible.builtin.command:
        cmd: grep -i '{{ 'P_True' if (k3s_controller_list | length > 1) else 'C_True' }}' /tmp/inventory.txt
      register: k3s_control_delegate_raw
    - name: Ensure control node is delegated for obtaining a cluster token
      when: k3s_control_delegate is not defined
      check_mode: false
      ansible.builtin.set_fact:
        k3s_control_delegate: "{{ k3s_control_delegate_raw.stdout.split(' @@@ ')[0] }}"
    - name: Ensure the node registration address is defined from k3s_control_node_address
      when: k3s_control_node_address is defined
      check_mode: false
      ansible.builtin.set_fact:
        k3s_registration_address: "{{ k3s_control_node_address }}"
    - name: Ensure the node registration address is defined from node-ip
      when:
        - k3s_registration_address is not defined
        - k3s_control_node_address is not defined
        - hostvars[k3s_control_delegate].k3s_node_ip is defined
      check_mode: false
      ansible.builtin.set_fact:
        k3s_registration_address: "{{ hostvars[k3s_control_delegate].k3s_node_ip }}"
    - name: Ensure the node registration address is defined
      when:
        - k3s_registration_address is not defined
        - k3s_control_node_address is not defined
      check_mode: false
      ansible.builtin.set_fact:
        k3s_registration_address: >
          {{
            hostvars[k3s_control_delegate].ansible_host
            | default(hostvars[k3s_control_delegate].ansible_fqdn)
          }}
- name: Configure sysctl
  block:
    - name: Configure fs.inotify.max_user_instances
      ansible.posix.sysctl:
        name: fs.inotify.max_user_instances
        value: "{{ k3s_inotify_max_user_instances }}"
        sysctl_file: "{{ k3s_sysctl_inotify_file }}"
        state: present
        reload: true
    - name: Configure fs.inotify.max_user_watches
      ansible.posix.sysctl:
        name: fs.inotify.max_user_watches
        value: "{{ k3s_inotify_max_user_watches }}"
        sysctl_file: "{{ k3s_sysctl_inotify_file }}"
        state: present
        reload: true
