---
- name: Check that k3s tls directory exists
  failed_when: >-
    not k3s_tls_path.stat.exists
    or not k3s_tls_path.stat.isdir
  ansible.builtin.stat:
    path: "{{ k3s_tls_dir }}"
  register: k3s_tls_path
- name: Copy root-ca.pem
  ansible.builtin.copy:
    src: "{{ ca_root_certs_path }}/root-ca.pem"
    dest: "{{ k3s_tls_dir }}/root-ca.pem"
    mode: u=rw,g=r,o=
  no_log: "{{ do_not_log }}"
- name: Copy root-ca.key
  ansible.builtin.copy:
    src: "{{ ca_root_certs_path }}/root-ca.key"
    dest: "{{ k3s_tls_dir }}/root-ca.key"
    mode: u=rw,g=r,o=
  no_log: "{{ do_not_log }}"
- name: Copy root-ca.crt
  ansible.builtin.copy:
    src: "{{ ca_root_certs_path }}/root-ca.crt"
    dest: "{{ k3s_tls_dir }}/root-ca.crt"
    mode: u=rw,g=r,o=
  no_log: "{{ do_not_log }}"
- name: Copy intermediate-ca.pem
  ansible.builtin.copy:
    src: "{{ ca_root_certs_path }}/intermediate-ca.pem"
    dest: "{{ k3s_tls_dir }}/intermediate-ca.pem"
    mode: u=rw,g=r,o=
  no_log: "{{ do_not_log }}"
- name: Copy intermediate-ca.key
  ansible.builtin.copy:
    src: "{{ ca_root_certs_path }}/intermediate-ca.key"
    dest: "{{ k3s_tls_dir }}/intermediate-ca.key"
    mode: u=rw,g=r,o=
  no_log: "{{ do_not_log }}"
- name: Copy intermediate-ca.crt
  ansible.builtin.copy:
    src: "{{ ca_root_certs_path }}/intermediate-ca.crt"
    dest: "{{ k3s_tls_dir }}/intermediate-ca.crt"
    mode: u=rw,g=r,o=
  no_log: "{{ do_not_log }}"
- name: Download k3s certs from custom CA generator
  ansible.builtin.get_url:
    url: https://github.com/k3s-io/k3s/raw/master/contrib/util/generate-custom-ca-certs.sh
    dest: /usr/local/bin/generate-custom-ca-certs.sh
    mode: u=rwx,g=rx,o=r
- name: Generate k3s certs from custom CA
  ansible.builtin.command:
    cmd: /usr/local/bin/generate-custom-ca-certs.sh
    chdir: "{{ k3s_tls_dir }}"
    creates: "{{ k3s_tls_dir }}/etcd/server-ca.crt"
  no_log: "{{ do_not_log }}"
  register: custom_ca_result
  changed_when: false
  failed_when:
    - custom_ca_result.rc != 0
    - "'CA certificate generation complete.' not in custom_ca_result.stdout_lines"
  environment:
    PRODUCT: "{{ project_domain }}"
    DATA_DIR: "/var/lib/rancher/k3s"
    TIMESTAMP: "{{ ca_root_certs_timestamp }}"
- name: Save custom_ca_result.stdout checksum
  ansible.builtin.copy:
    content: "{{ custom_ca_result.stdout | ansible.builtin.checksum }}"
    dest: /usr/local/bin/generate-custom-ca-certs.sh.checksum
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: u=rw,go=r
