---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-env-cm
data:
  POSTGRES_USER: postgres
  POSTGRES_DB: postgres
  POSTGRES_SSLMODE: disable
  PGDATA: /var/lib/postgresql/data
  POSTGRES_INITDB_ARGS: '--lc-collate=en_US.utf8 --lc-ctype=en_US.utf8'
