---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-db-init-pv
  labels:
    app: postgres
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/local/assets/postgres
