apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: postgres-config
        image: postgres:13-alpine
        name: postgres
        ports:
        - containerPort: 5432
          name: pg-port
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data-volume
        - mountPath: /docker-entrypoint-initdb.d
          name: postgres-db-init-volume
      volumes:
      - name: postgres-data-volume
        persistentVolumeClaim:
          claimName: postgres-data-pvc
      - name: postgres-db-init-volume
        persistentVolumeClaim:
          claimName: postgres-db-init-pvc
