---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app: postgres
    app.kubernetes.io/component: database
    role: data
- includeSelectors: false
  pairs:
    app.kubernetes.io/version: "16.2"

resources:
- configmap.yaml
- secret.yaml
- service.yaml
- service-headless.yaml
- serviceaccount.yaml
- statefulset.yaml
