---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc-headless
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: postgres
  ports:
  - name: postgres-port
    port: 5432
    protocol: TCP
    targetPort: postgres-port
