---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  type: ClusterIP
  ports:
    - name: pg-port
      port: 5432
      protocol: TCP
      targetPort: postgres-port
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    role: data
