---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-data-pv
  labels:
    type: local
    app: postgres
spec:
  storageClassName: local-path
  capacity:
    storage: 15Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /var/local/data/postgres
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-data-pvc
  labels:
    app: postgres
spec:
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: postgres-data-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
