---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app: terrakube-executor

resources:
- configmap.yaml
- deployment.yaml
- secrets.yaml
- service.yaml
