---
apiVersion: v1
kind: Service
metadata:
  name: terrakube-executor-svc
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: terrakube-executor
  ports:
  - port: 8090
    targetPort: 8090
