resources:
- namespaces.yaml
- ../../platform/kind
- ../../crd/cert-manager
- ../../apps/certificates
- ../../apps/ingress-nginx
- ../../apps/gitea
- ../../apps/harbor

patchesJson6902:
- target:
    version: v1
    kind: ConfigMap
    name: tcp-services
  path: patch.yaml
