resources:
- namespaces.yaml
- ../../platform/kind
- ../../crd/cert-manager
- github.com/zalando/postgres-operator/manifests
- ../../crd/redis-operator
- ../../crd/harbor-operator
- ../../apps/certificates
- ../../apps/nginx-ingress
- ../../apps/gitea
- ../../apps/harbor

patchesJson6902:
- target:
    version: v1
    kind: ConfigMap
    name: tcp-services
  path: patch.yaml