resources:
- namespaces.yaml
- ../../platform/kind
- ../../apps/certificates
- ../../apps/nginx-ingress
- ../../apps/gitea

patchesJson6902:
- target:
    version: v1
    kind: ConfigMap
    name: tcp-services
  path: patch.yaml