---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-portal
spec:
  replicas: 1
  revisionHistoryLimit: 10
  template:
    spec:
      securityContext:
        runAsUser: 10000
        fsGroup: 10000
      automountServiceAccountToken: false
      containers:
      - name: portal
        image: goharbor/harbor-portal:v2.10.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            scheme: HTTPS
            port: 8443
          initialDelaySeconds: 300
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            scheme: HTTPS
            port: 8443
          initialDelaySeconds: 1
          periodSeconds: 10
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: portal-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: portal-internal-certs
          mountPath: /etc/harbor/ssl/portal
      volumes:
      - name: portal-config
        configMap:
          name: "harbor-portal"
      - name: portal-internal-certs
        secret:
          secretName: harbor-portal-internal-tls
