---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    component: portal
    app.kubernetes.io/name: harbor-portal
resources:
- configmap.yaml
- deployment.yaml
- service.yaml
