---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: application
    app.kubernetes.io/instance: keycloak

resources:
- configmap.yaml
- data-pvc.yaml
- ingress-admin.yaml
- ingress.yaml
- service-headless.yaml
- service.yaml
- serviceaccount.yaml
- statefulset.yaml

secretGenerator:
- name: keycloak-env-secret
  literals:
  - KC_BOOTSTRAP_ADMIN_USERNAME=keycloak
  - KC_BOOTSTRAP_ADMIN_PASSWORD=password1234

generatorOptions:
  disableNameSuffixHash: true
