---
apiVersion: v1
kind: ConfigMap
metadata:
  name: terrakube-files
data:
  README.md: |-
    ## Secret Files
    All files included in this directory will be inside the kubernetes ConfigMap ***terrakube-files***. Kubernetes has a ConfigMap size limit of 1MB.
    > This is useful when we need to upload some extra files to the helm chart.
  ca-certificates-type: |-
    ca-certificates
