---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: gitea
resources:
  - gitea
  - redis
  - postgres
configurations:
  - references-override.yaml
