---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tools

labels:

- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: gitea

resources:
- gitea
- redis
- postgres

patches:
- path: patches/gitea-env-cm.yaml

replacements:
- path: patches/gitea-db-name.yaml
- path: patches/gitea-db-password.yaml
- path: patches/gitea-db-user.yaml
