---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tools

labels:

- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: forgejo

resources:
- forgejo
- redis
- postgres

patches:
- path: patches/forgejo-env-cm.yaml

replacements:
- path: patches/forgejo-db-name.yaml
- path: patches/forgejo-db-password.yaml
- path: patches/forgejo-db-user.yaml
