apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: harbor
    component: exporter
  name: harbor-exporter
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: harbor
      component: exporter
  template:
    metadata:
      labels:
        app: harbor
        component: exporter
    spec:
      automountServiceAccountToken: false
      containers:
      - args:
        - "-log-level"
        - info
        envFrom:
        - configMapRef:
            name: harbor-exporter-env
        - secretRef:
            name: harbor-exporter
        image: goharbor/harbor-exporter:v2.5.2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 300
          periodSeconds: 10
        name: exporter
        ports:
        - containerPort: 8443
        readinessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - mountPath: /etc/harbor/ssl/core
          name: core-internal-certs
      securityContext:
        fsGroup: 10000
        runAsUser: 10000
      volumes:
      - name: config
        secret:
          secretName: harbor-exporter
      - name: core-internal-certs
        secret:
          secretName: harbor-core-internal-tls
