apiVersion: v1
data:
  HARBOR_DATABASE_DBNAME: registry
  HARBOR_DATABASE_HOST: harbor-database
  HARBOR_DATABASE_MAX_IDLE_CONNS: "100"
  HARBOR_DATABASE_MAX_OPEN_CONNS: "900"
  HARBOR_DATABASE_PORT: "5432"
  HARBOR_DATABASE_SSLMODE: disable
  HARBOR_DATABASE_USERNAME: postgres
  HARBOR_EXPORTER_CACHE_CLEAN_INTERVAL: "14400"
  HARBOR_EXPORTER_CACHE_TIME: "23"
  HARBOR_EXPORTER_METRICS_ENABLED: "true"
  HARBOR_EXPORTER_METRICS_PATH: /metrics
  HARBOR_EXPORTER_PORT: "8001"
  HARBOR_METRIC_NAMESPACE: harbor
  HARBOR_METRIC_SUBSYSTEM: exporter
  HARBOR_REDIS_NAMESPACE: harbor_job_service_namespace
  HARBOR_REDIS_TIMEOUT: "3600"
  HARBOR_REDIS_URL: redis://harbor-redis:6379/1
  HARBOR_SERVICE_HOST: harbor-core
  HARBOR_SERVICE_PORT: "443"
  HARBOR_SERVICE_SCHEME: https
  HTTPS_PROXY: ""
  HTTP_PROXY: ""
  LOG_LEVEL: info
  NO_PROXY: harbor-core,harbor-jobservice,harbor-database,harbor-chartmuseum,notary-server,notary-signer,harbor-registry,harbor-portal,harbor-trivy,harbor-exporter,127.0.0.1,localhost,.local,.internal
kind: ConfigMap
metadata:
  labels:
    app: harbor
  name: harbor-exporter-env
