---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drone-data-pvc
  labels:
    app: drone
spec:
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: drone-data-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
