---
source:
  kind: Secret
  name: terrakube-openldap-env-secrets
  fieldPath: data.LDAP_ADMIN_PASSWORD
targets:
- select:
    kind: Secret
    name: terrakube-dex-env-secrets
  fieldPaths:
  - data.LDAP_ADMIN_PASSWORD
  options:
    create: true
