---
source:
  kind: Secret
  name: terrakube-postgres-env-secrets
  fieldPath: data.POSTGRES_PASSWORD
targets:
- select:
    kind: Secret
    name: terrakube-api-env-secrets
  fieldPaths:
  - data.DatasourcePassword
  options:
    create: true
