---
source:
  kind: ConfigMap
  name: terrakube-postgres-env-cm
  fieldPath: data.POSTGRES_USER
targets:
- select:
    kind: ConfigMap
    name: terrakube-api-env-cm
  fieldPaths:
  - data.DatasourceUser
  options:
    create: true
