---
source:
  kind: Secret
  name: terrakube-redis-env-secret
  fieldPath: data.PASSWORD
targets:
- select:
    kind: Secret
    name: terrakube-api-env-secrets
  fieldPaths:
  - data.TerrakubeRedisPassword
  options:
    create: true
- select:
    kind: Secret
    name: terrakube-executor-env-secrets
  fieldPaths:
  - data.TerrakubeRedisPassword
  options:
    create: true
