---
source:
  kind: Secret
  name: terrakube-s3-credentials
  fieldPath: data.password
targets:
- select:
    kind: Secret
    name: terrakube-api-env-secrets
  fieldPaths:
  - data.AwsStorageSecretKey
  options:
    create: true
- select:
    kind: Secret
    name: terrakube-executor-env-secrets
  fieldPaths:
  - data.AwsTerraformStateSecretKey
  options:
    create: true
- select:
    kind: Secret
    name: terrakube-executor-env-secrets
  fieldPaths:
  - data.AwsTerraformOutputSecretKey
  options:
    create: true
- select:
    kind: Secret
    name: terrakube-registry-env-secrets
  fieldPaths:
  - data.AwsStorageSecretKey
  options:
    create: true
