apiVersion: v1
data:
  ALLOW_OVERWRITE: "true"
  AUTH_ANONYMOUS_GET: "false"
  BASIC_AUTH_USER: chart_controller
  CACHE: redis
  CACHE_REDIS_ADDR: harbor-redis:6379
  CACHE_REDIS_DB: "3"
  CHART_POST_FORM_FIELD_NAME: chart
  CONTEXT_PATH: ""
  DEBUG: "false"
  DEPTH: "1"
  DISABLE_API: "false"
  DISABLE_METRICS: "false"
  DISABLE_STATEFILES: "false"
  INDEX_LIMIT: "0"
  LOG_JSON: "true"
  MAX_STORAGE_OBJECTS: "0"
  MAX_UPLOAD_SIZE: "20971520"
  PORT: "9443"
  PROV_POST_FORM_FIELD_NAME: prov
  STORAGE: local
  STORAGE_LOCAL_ROOTDIR: /chart_storage
  STORAGE_TIMESTAMP_TOLERANCE: 1s
  TLS_CERT: /etc/harbor/ssl/chartmuseum/tls.crt
  TLS_KEY: /etc/harbor/ssl/chartmuseum/tls.key
kind: ConfigMap
metadata:
  labels:
    app: harbor
  name: harbor-chartmuseum
