apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: harbor
    component: chartmuseum
  name: harbor-chartmuseum
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
