---
apiVersion: v1
kind: Secret
metadata:
  name: wazuh-api-cred
data:
  username: d2F6dWgtd3Vp          # string "wazuh-wui" base64 encoded
  password: TXlTM2NyMzdQNDUwci4qLQ==  # string "MyS3cr37P450r.*-" base64 encoded
