apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: tools
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:18.0.2
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 128Mi
        args:
        - start-dev
        envFrom:
        - configMapRef:
            name: keycloak-config
        - secretRef:
            name: keycloak-secret
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080
        volumeMounts:
        - mountPath: /opt/keycloak/data
          name: keycloak-data-volume
      volumes:
      - name: keycloak-data-volume
        persistentVolumeClaim:
          claimName: keycloak-data-pvc
