---
# Source: tempo-distributed/templates/querier/service-querier.yaml
apiVersion: v1
kind: Service
metadata:
  name: tempo-querier
  labels:
    app.kubernetes.io/component: querier
spec:
  ports:
    - name: http-metrics
      port: 3100
      protocol: TCP
      targetPort: 3100
    - name: grpc
      port: 9095
      protocol: TCP
      targetPort: 9095
  selector:
    app.kubernetes.io/component: querier
