---
apiVersion: v1
kind: Service
metadata:
  name: tempo-querier
  labels:
    app.kubernetes.io/name: tempo-querier
    app.kubernetes.io/component: querier
    prometheus.io/service-monitor: "true"
spec:
  ports:
  - name: http-metrics
    port: 3100
    protocol: TCP
    targetPort: http-metrics
  - name: grpc
    port: 9095
    protocol: TCP
    targetPort: grpc
  selector:
    app.kubernetes.io/component: querier
