---
apiVersion: v1
kind: Service
metadata:
  name: tempo-compactor
  labels:
    app.kubernetes.io/component: compactor
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 3100
      targetPort: 3100
      protocol: TCP
  selector:
    app.kubernetes.io/component: compactor
