apiVersion: v1
kind: Service
metadata:
  labels:
    app: harbor
  name: harbor-core
spec:
  ports:
  - name: https-web
    port: 443
    targetPort: 8443
  - name: https-metrics
    port: 8001
  selector:
    app: harbor
    component: core
