---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: harbor
  name: harbor-trivy
spec:
  ports:
  - name: https-trivy
    port: 8443
    protocol: TCP
  selector:
    app: harbor
    component: trivy
