kind: PersistentVolume
apiVersion: v1
metadata:
  name: keycloak-data-pv
  namespace: tools
  labels:
    type: local
    app: keycloak
spec:
  storageClassName: local-path
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /var/local/keycloak
