---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app: wazuh-manager

resources:
- wazuh-cluster-svc.yaml
- wazuh-master-svc.yaml
- wazuh-workers-svc.yaml
- wazuh-master-sts.yaml
- wazuh-worker-sts.yaml
