---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-data-pv
  labels:
    type: local
    app: redis
spec:
  storageClassName: local-path
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/local/data/redis
