---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app: redis
      app.kubernetes.io/component: cache
resources:
  - data-pv.yaml
  - service.yaml
  - statefulset.yaml
