---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    component: redis
spec:
  ports:
  - name: redis-port
    protocol: TCP
    port: 6379
  selector:
    app: redis
    component: redis
