---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc-headless
  labels:
    app.kubernetes.io/name: redis-svc-headless
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: redis
  ports:
  - name: redis-port
    port: 6379
    protocol: TCP
    targetPort: redis-port
