---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  labels:
    app.kubernetes.io/name: redis-svc
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: redis
  ports:
  - name: redis-port
    port: 6379
    protocol: TCP
    targetPort: redis-port
