---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc-headless
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: redis-port
    port: 6379
    protocol: TCP
    targetPort: redis-port
