apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: redis
    component: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      component: redis
  serviceName: redis-service
  template:
    metadata:
      labels:
        app: redis
        component: redis
    spec:
      automountServiceAccountToken: false
      containers:
      - image: redis:7.0.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 10
          tcpSocket:
            port: 6379
        name: redis
        readinessProbe:
          initialDelaySeconds: 1
          periodSeconds: 10
          tcpSocket:
            port: 6379
        volumeMounts:
        - mountPath: /var/lib/redis
          name: data
      securityContext:
        fsGroup: 999
        runAsUser: 999
      terminationGracePeriodSeconds: 120
  volumeClaimTemplates:
  - metadata:
      labels:
        app: redis
      name: data
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 1Gi
