---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: redis
  replicas: 1
  serviceName: redis-svc-headless
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: redis
    spec:
      serviceAccountName: redis
      containers:
      - name: redis
        image: redis:7
        imagePullPolicy: Always
        ports:
        - name: redis-port
          containerPort: 6379
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 10
          tcpSocket:
            port: 6379
        readinessProbe:
          initialDelaySeconds: 1
          periodSeconds: 10
          tcpSocket:
            port: 6379
        volumeMounts:
        - name: data
          mountPath: /var/lib/redis
      securityContext:
        fsGroup: 999
        runAsUser: 999
      terminationGracePeriodSeconds: 120
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: "8Gi"
