---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: opa
  name: opa-policy-pvc
  namespace: tools
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: opa-policy-pv
