---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: opa
    type: local
  name: opa-policy-pv
  namespace: tools
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 15Gi
  hostPath:
    path: /var/local/data/opa-policies
  storageClassName: local-path
