---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: opa
  name: opa
  namespace: tools
spec:
  ports:
  - name: http
    port: 8181
    protocol: TCP
    targetPort: 8181
  selector:
    app: opa
