kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: tools
  name: certs-pv
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/var/local/certs"