# patchesJson6902:
# - path: patch.yaml
#   target:
#     kind: ConfigMap
#     name: tcp-services
#     version: v1
resources:
# - ../../apps/gitea
- ../../apps/keycloak
# - ../../apps/notary
# - ../../apps/drone
# - ../../apps/harbor
