---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: vault
  name: vault-data-pvc
  namespace: tools
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: vault-data-pv
