---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: vault
    type: local
  name: vault-data-pv
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 500Gi
  hostPath:
    path: /var/local/data/vault-data
