apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitea
  name: gitea
  namespace: tools
spec:
  ports:
  - name: gitea-http
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: gitea-ssh
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: gitea
