---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tools

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: tacos

resources:
- ../../clusters/iam-demo-tech/bootstrap/configurations/base/secrets/terrakube-s3-credentials
- dex
- openldap
- postgres
- redis
- terrakube
- terrakube-api
- terrakube-executor
- terrakube-registry
- terrakube-ui

replacements:
- path: patches/postgres-db-name.yaml
- path: patches/postgres-db-password.yaml
- path: patches/postgres-db-user.yaml
- path: patches/redis-password.yaml
- path: patches/s3-access-key.yaml
- path: patches/s3-secret-key.yaml
