---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: tempo-

resources:
- ../../../base/memcached

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/serviceAccountName
      value: tempo
  target:
    group: apps
    version: v1
    kind: StatefulSet
    labelSelector: "app.kubernetes.io/component=memcached-server"
