---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: tempo-

labels:
- includeSelectors: true
  pairs:
    app: memcached

resources:
- ../../../base/memcached

patches:
- path: patch-statefulset.yaml
