---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app: midpoint
    app.kubernetes.io/app: midpoint
    app.kubernetes.io/component: application

resources:
- configmap.yaml
- configmap-repository.yaml
- ingress.yaml
- secrets.yaml
- secrets-repository.yaml
- service.yaml
- statefulset.yaml

secretGenerator:
- name: midpoint-env-secrets
  behavior: merge
  literals:
  - MP_SET_midpoint_administrator_initialPassword=Test5ecr3t

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app: midpoint
