---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: keycloak
  name: keycloak-data-pvc
  namespace: tools
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: keycloak-data-pv
