---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-config-pvc
  labels:
    app.kubernetes.io/name: gitea-config-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
