apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-data-pv
  labels:
    app.kubernetes.io/name: gitea-data-pv
    type: local
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /var/local/data/gitea
  storageClassName: local-path
