---
apiVersion: v1
kind: Service
metadata:
  name: gitea-http
  labels:
    app.kubernetes.io/name: gitea-http
    app.kubernetes.io/component: service
spec:
  ports:
    - name: gitea-http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: gitea
