---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-inline-config
  labels:
    app.kubernetes.io/name: gitea-inline-config
type: Opaque
stringData:
  _generals_: ""
  cache: |-
    ADAPTER=redis
    HOST=redis+cluster://:@gitea-redis-cluster-headless.tools.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s&
  database: |-
    DB_TYPE=postgres
    HOST=gitea-postgresql-ha-pgpool.tools.svc.cluster.local:5432
    NAME=gitea
    PASSWD=gitea
    USER=gitea
  indexer: ISSUE_INDEXER_TYPE=db
  metrics: ENABLED=false
  queue: |-
    CONN_STR=redis+cluster://:@gitea-redis-cluster-headless.tools.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s&
    TYPE=redis
  repository: ROOT=/data/git/gitea-repositories
  security: INSTALL_LOCK=true
  server: |-
    APP_DATA_PATH=/data
    DOMAIN=git.example.com
    ENABLE_PPROF=false
    HTTP_PORT=3000
    PROTOCOL=http
    ROOT_URL=http://git.example.com
    SSH_DOMAIN=git.example.com
    SSH_LISTEN_PORT=2222
    SSH_PORT=22
    START_SSH_SERVER=true
  session: |-
    PROVIDER=redis
    PROVIDER_CONFIG=redis+cluster://:@gitea-redis-cluster-headless.tools.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s&
