---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: vault-agent-injector-cfg
  labels:
    app.kubernetes.io/name: vault-agent-injector
    app.kubernetes.io/instance: vault
webhooks:
- name: vault.hashicorp.com
  failurePolicy: Ignore
  matchPolicy: Exact
  sideEffects: None
  timeoutSeconds: 30
  admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: vault-agent-injector-svc
      namespace: security
      path: /mutate
    caBundle: ''
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - ''
    apiVersions:
    - v1
    resources:
    - pods
  objectSelector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: NotIn
      values:
      - vault-agent-injector
