---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-agent-injector
  namespace: monitoring
  labels:
    app.kubernetes.io/name: vault-agent-injector
    app.kubernetes.io/instance: vault
