---
source:
  kind: Secret
  name: keycloak-postgres-env-secrets
  fieldPath: data.POSTGRES_PASSWORD
targets:
- select:
    kind: Secret
    name: keycloak-env-secret
  fieldPaths:
  - data.KC_DB_PASSWORD
  options:
    create: true
