apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
labels:
  - includeSelectors: false
    pairs:
      app: gitea
      app.kubernetes.io/version: 1.21.5
      version: 1.21.5
resources:
  - configmaps/gitea-config.yaml
  - deployments/gitea.yaml
  - ingresses/gitea-ingress.yaml
  - persistentvolume/gitea-data-pv.yaml
  - persistentvolumeclaims/gitea-data-pvc.yaml
  - secrets/gitea-inline-config.yaml
  - secrets/gitea-init.yaml
  - secrets/gitea-secrets.yaml
  - servicemonitor/gitea.yaml
  - services/gitea-http.yaml
  - services/gitea-ssh.yaml
