# Full stack Harbor
apiVersion: goharbor.io/v1beta1
kind: HarborCluster
metadata:
  name: harborcluster-demo
  namespace: harbor-demo
spec:
  version: 2.5.1
  logLevel: info
  network:
    ipFamilies:
      - IPv4
      - IPv6
  imageSource:
    repository: ghcr.io/goharbor
  harborAdminPasswordRef: admin-core-secret
  externalURL: https://core.harbor.iam-demo.test
  expose:
    core:
      ingress:
        host: core.harbor.iam-demo.test
        controller: default
      tls:
        certificateRef: harbor-demo-certificate
    notary:
      ingress:
        host: notary.harbor.iam-demo.test
        controller: default
      tls:
        certificateRef: harbor-demo-certificate
  internalTLS:
    enabled: true
  portal: {}
  registry:
    metrics:
      enabled: true
  core:
    tokenIssuer:
      name: selfsigned-issuer
      kind: Issuer
    metrics:
      enabled: true
  chartmuseum: {}
  exporter: {}
  trivy:
    skipUpdate: false
    storage:
      cachePersistentVolume:
        claimName: harbor-data-pvc
        prefix: trivy-cache
      reportsPersistentVolume:
        claimName: harbor-data-pvc
        prefix: trivy-reports
  notary:
    migrationEnabled: true
  database:
    kind: Zlando/PostgreSQL
    spec:
      zlandoPostgreSql:
        operatorVersion: "1.5.0"
        storage: 1Gi
        replicas: 1
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 250Mi
  storage:
    kind: FileSystem
    spec:
      fileSystem:
        chartPersistentVolume:
          claimName: harbor-data-pvc
          prefix: chart
        registryPersistentVolume:
          claimName: harbor-data-pvc
          prefix: registry
  cache:
    kind: RedisFailover
    spec:
      redisFailover:
        operatorVersion: "1.1.0"
        server:
          replicas: 1
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 250Mi
        sentinel:
          replicas: 1
        # storage:
        #   keepAfterDeletion: true
        #   persistentVolumeClaim:
        #     metadata:
        #       name: demo-harbor-redisfailover
        #     spec:
        #       accessModes:
        #         - ReadWriteOnce
        #       resources:
        #         requests:
        #           storage: 1Gi
