kind: PersistentVolume
apiVersion: v1
metadata:
  name: harbor-data-pv
  labels:
    type: local
    app: harbor
spec:
  storageClassName: local-path
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/local/harbor"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-data-pvc
  labels:
    demo: "true"
    app: harbor
spec:
  storageClassName: local-path
  volumeName: harbor-data-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: demo-harbor-registry
#   labels:
#     demo: "true"
#     app: harbor
# spec:
#   storageClassName: local-path
#   volumeName: harbor-data-pv
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 50Gi
#   volumeMode: Filesystem
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: demo-harbor-redisfailover
#   labels:
#     demo: "true"
#     app: harbor
# spec:
#   storageClassName: local-path
#   volumeName: harbor-data-pv
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 1Gi
#   volumeMode: Filesystem
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: demo-harbor-trivy-cache
#   labels:
#     demo: "true"
#     app: harbor
# spec:
#   storageClassName: local-path
#   volumeName: harbor-data-pv
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 50Gi
#   volumeMode: Filesystem
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: demo-harbor-trivy-reports
#   labels:
#     demo: "true"
#     app: harbor
# spec:
#   storageClassName: local-path
#   volumeName: harbor-data-pv
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 50Gi
#   volumeMode: Filesystem
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: demo-harbor-chart
#   labels:
#     demo: "true"
#     app: harbor
# spec:
#   storageClassName: local-path
#   volumeName: harbor-data-pv
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 50Gi
#   volumeMode: Filesystem
