---
source:
  kind: ConfigMap
  name: midpoint-postgres-env-cm
  fieldPath: data.POSTGRES_DB
targets:
- select:
    kind: ConfigMap
    name: midpoint-repository-env-cm
  fieldPaths:
  - data.MP_DATABASE_NAME
  options:
    create: true
