---
source:
  kind: Secret
  name: midpoint-postgres-env-secrets
  fieldPath: data.POSTGRES_PASSWORD
targets:
- select:
    kind: Secret
    name: midpoint-repository-env-secrets
  fieldPaths:
  - data.MP_SET_midpoint_repository_jdbcPassword
  options:
    create: true
