---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app: terrakube-registry
    app.kubernetes.io/app: terrakube-registry
    app.kubernetes.io/component: registry

resources:
- configmap.yaml
- deployment.yaml
- ingress.yaml
- secrets.yaml
- service.yaml
