---
- name: Configure k3s
  become: true
  block:
    - name: Pre check validation
      ansible.builtin.import_tasks: pre_checks/validate.yml
    - name: Run task {{ k3s_state }}
      ansible.builtin.include_tasks: state/{{ k3s_state }}.yml
