---
source:
  kind: ConfigMap
  name: forgejo-postgres-env-cm
  fieldPath: data.POSTGRES_USER
targets:
- select:
    kind: ConfigMap
    name: forgejo-env-cm
  fieldPaths:
  - data.FORGEJO__DATABASE__USER
  options:
    create: true
