---
source:
  kind: Secret
  name: forgejo-postgres-env-secrets
  fieldPath: data.POSTGRES_PASSWORD
targets:
- select:
    kind: Secret
    name: forgejo-env-secrets
  fieldPaths:
  - data.FORGEJO__DATABASE__PASSWD
  options:
    create: true
