---
source:
  kind: ConfigMap
  name: gitea-postgres-env-cm
  fieldPath: data.POSTGRES_USER
targets:
- select:
    kind: ConfigMap
    name: gitea-env-cm
  fieldPaths:
  - data.GITEA__DATABASE__USER
  options:
    create: true
