---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-exporter
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
  template:
    spec:
      securityContext:
        runAsUser: 10000
        fsGroup: 10000
      automountServiceAccountToken: false
      containers:
      - name: exporter
        image: goharbor/harbor-exporter:v2.10.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 300
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        args: ["-log-level", "info"]
        envFrom:
        - configMapRef:
            name: "harbor-exporter-env"
        - secretRef:
            name: "harbor-exporter"
        env:
        - name: HARBOR_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: harbor-postgres-secrets
              key: password
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: core-internal-certs
          mountPath: /etc/harbor/ssl/core
          # There are some metric data are collectd from harbor core.
          # When internal TLS is enabled, the Exporter need the CA file to collect these data.
      volumes:
      - name: config
        secret:
          secretName: "harbor-exporter"
      - name: core-internal-certs
        secret:
          secretName: harbor-core-internal-tls
