---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: terrakube-

resources:
- ../../../base/openldap

secretGenerator:
- name: openldap-ldif-files-secrets
  behavior: merge
  files:
  - config-ldap.ldif=assets/config-ldap.ldif
