---
- name: Configure k3s
  block:
    - name: Pre check validation
      ansible.builtin.import_tasks: pre_checks/validate.yml
    - name: Run task {{ playground_example }}
      ansible.builtin.include_tasks: examples/{{ playground_example }}/main.yml
