---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: notary-signer
  name: notary-signer
  namespace: tools
spec:
  ports:
  - port: 7899
  selector:
    app: notary
    component: notary-signer
