apiVersion: v1
kind: Service
metadata:
  labels:
    component: notary-server
  name: notary-server
  namespace: tools
spec:
  ports:
  - port: 4443
  selector:
    app: notary
    component: notary-server
