---
k3s_primary_control_node: true
iam_tech_cluster_name: iam-demo-tech
kubernetes_project_path: /kubernetes
kubernetes_dashboard_path: "{{ kubernetes_project_path }}/apps/kubernetes-dashboard"
kustomize_project_path: "{{ kubernetes_project_path }}/clusters/{{ iam_tech_cluster_name }}/bootstrap"
kubernetes_cluster_config_path: "{{ kubernetes_project_path }}/clusters_config/{{ k3s_cluster_name }}"
python_libraries:
  - dnspython
k3s_copy_cluster_config:
  - name: 'iam-demo-tech'
    users:
      - ansible
      - iamadmin
      - ubuntu
