---
k3s_copy_cluster_config:
  - name: iam-demo-tech
    users:
      - ansible
      - iamadmin
      - ubuntu
use_selfsigned_root_ca: true
is_linux_desktop: true
desktop_user: iamadmin
additional_packages:
  - firefox
