---
k3s_copy_cluster_config:
  - name: iam-demo-tech
    users:
      - ansible
      - iamadmin
      - ubuntu
use_selfsigned_root_ca: true
is_linux_desktop: true
desktop_user: iamadmin
additional_packages:
  - firefox

firefox_managed_bookmarks:
  - toplevel_name: Managed bookmarks
  - url: https://keycloak.iam-demo.test/
    name: Login
  - name: Tools
    children:
      - url: https://alertmanager.iam-demo.test/
        name: Alertmanager
      - url: https://consul.iam-demo.test/
        name: Consul
      - url: https://git.iam-demo.test/
        name: Forgejo
      - url: https://grafana.iam-demo.test/
        name: Grafana
      - url: https://mail.iam-demo.test/
        name: Mailpit
      - url: https://midpoint.iam-demo.test/
        name: midPoint (IGA)
      - url: https://minio.iam-demo.test/
        name: MinIO (S3)
      - url: https://prometheus.iam-demo.test/
        name: Prometheus
      - url: https://terrakube-ui.iam-demo.test/
        name: Terrakube (TACOS)
      - url: https://vault.iam-demo.test/
        name: Vault
  - name: Tools (local proxy)
    children:
      - url: http://127.0.0.1:9000/dashboard/
        name: Traefik Dashboard
      - url: https://localhost:8443
        name: Kubernetes Dashboard
  - name: Extra
    children:
      - url: https://loki.iam-demo.test/memberlist
        name: Loki memberlist
  - name: Documentation
    children:
      - url: https://github.com/sinetris/iam-demo
        name: IAM Demo on GitHub

firefox_preferences:
  - name: geo.enabled
    value: false
  - name: mousewheel.default.delta_multiplier_y
    value: 25
