---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailpit-data-pvc
  labels:
    app.kubernetes.io/name: mailpit-data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
