---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tools

labels:
- includeSelectors: true
  pairs:
    app: mailpit
    role: smtp

resources:
- configmap-env.yaml
- data-pvc.yaml
- deployment.yaml
- ingress.yaml
- secrets-authfiles.yaml
- service-http.yaml
- service-smtp.yaml
