---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tools

labels:
- includeSelectors: true
  pairs:
    app: mailpit
    app.kubernetes.io/app: mailpit
    app.kubernetes.io/part-of: mailpit

resources:
- configmap-env.yaml
- data-pvc.yaml
- deployment.yaml
- ingress.yaml
- secrets-authfiles.yaml
- service-pop3.yaml
- service-smtp.yaml
- service-web.yaml
