---
- name: Check that k3s_state is a supported value
  ansible.builtin.assert:
    that:
      - k3s_state in k3s_valid_states
    fail_msg: "k3s_state '{{ k3s_state }}' not valid. Check README.md for details."
    success_msg: "k3s_state is valid."
