---
- name: Check that 'k3s_state' contains a valid value
  ansible.builtin.assert:
    that:
      - k3s_state in k3s_valid_states
    fail_msg: "Invalid k3s_state '{{ k3s_state }}'. Must be one of: {{ k3s_valid_states }}."
    success_msg: "Valid k3s_state: '{{ k3s_state }}'"
- name: Checks that the CA root certificate path exists in the ansible controller
  ansible.builtin.stat:
    path: "{{ ca_root_certs_path }}"
  delegate_to: localhost
  run_once: true
  failed_when: >-
    not check_ca_root_certs_path.stat.exists
    or not check_ca_root_certs_path.stat.isdir
  register: check_ca_root_certs_path
  when:
    - k3s_copy_ca_certs
    - not ansible_check_mode
