---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo-distributor
  labels:
    app.kubernetes.io/component: distributor
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: distributor
  template:
    metadata:
      labels:
        app.kubernetes.io/component: distributor
    spec:
      serviceAccountName: tempo
      securityContext:
        fsGroup: 1000
      enableServiceLinks: false
      containers:
      - name: distributor
        image: grafana/tempo:2.4.0
        imagePullPolicy: Always
        args:
        - -target=distributor
        - -config.file=/conf/tempo.yaml
        - -mem-ballast-size-mbs=1024
        - -config.expand-env=true
        ports:
        - containerPort: 7946
          name: http-memberlist
          protocol: TCP
        - containerPort: 3100
          name: http-metrics
        - containerPort: 4318
          name: otlp-http
          protocol: TCP
        - containerPort: 4317
          name: grpc-otlp
          protocol: TCP
        env:
        - name: MINIO_S3_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: minio-url
              key: internalEndpoint
        - name: MINIO_S3_ACCESKEYID
          valueFrom:
            secretKeyRef:
              name: tempo-s3-credentials
              key: user
        - name: MINIO_S3_SECRETACCESSKEY
          valueFrom:
            secretKeyRef:
              name: tempo-s3-credentials
              key: password
        readinessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 30
          timeoutSeconds: 1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
        volumeMounts:
        - mountPath: /conf
          name: config
        - mountPath: /runtime-config
          name: runtime-config
        - mountPath: /var/tempo
          name: tempo-distributor-store
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/component: distributor
      volumes:
      - name: config
        configMap:
          name: tempo-config
          items:
          - key: "tempo.yaml"
            path: "tempo.yaml"
      - name: runtime-config
        configMap:
          name: tempo-runtime
          items:
          - key: "overrides.yaml"
            path: "overrides.yaml"
      - name: tempo-distributor-store
        emptyDir: {}
