---
apiVersion: v1
kind: Service
metadata:
  name: tempo-distributor
  labels:
    app.kubernetes.io/name: tempo-distributor
    app.kubernetes.io/component: distributor
spec:
  type: ClusterIP
  ports:
  - name: http-metrics
    port: 3100
    targetPort: http-metrics
  - name: grpc
    port: 9095
    protocol: TCP
    targetPort: grpc
  - name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: otlp-http
  - name: otlp-grpc
    port: 4317
    protocol: TCP
    targetPort: otlp-grpc
  - name: legacy-otlp-grpc
    port: 55680
    protocol: TCP
    targetPort: otlp-grpc
  selector:
    app.kubernetes.io/name: tempo-distributor
    app.kubernetes.io/component: distributor
