---
- name: Install kubernetes-dashboard helm chart
  kubernetes.core.helm:
    name: kubernetes-dashboard
    state: present
    chart_ref: kubernetes-dashboard/kubernetes-dashboard
    update_repo_cache: true
    namespace: kubernetes-dashboard
    create_namespace: false
    timeout: 10m
    wait: true
    values_files:
      - "{{ kubernetes_cluster_config_path }}/helm-kubernetes-dashboard-values.yaml"
- name: Install Prometheus CRDs
  kubernetes.core.helm:
    name: prometheus-crds
    state: present
    chart_ref: prometheus-community/kube-prometheus-stack
    update_repo_cache: true
    namespace: observability
    create_namespace: true
    timeout: 10m
    wait: true
    values_files:
      - "{{ kubernetes_cluster_config_path }}/helm-prometheus-crds-values.yaml"
- name: Install cert-manager helm chart
  kubernetes.core.helm:
    name: cert-manager
    state: present
    chart_ref: jetstack/cert-manager
    update_repo_cache: true
    namespace: security
    create_namespace: true
    timeout: 10m
    wait: true
    values_files:
      - "{{ kubernetes_cluster_config_path }}/helm-cert-manager-values.yaml"
- name: Configure cert-manager cluster issuer
  kubernetes.core.k8s:
    definition: "{{ lookup('kubernetes.core.kustomize', dir=kustomize_files_path) }}"
  vars:
    kustomize_files_path: "{{ project_bootstrap_kustomize_path }}/clusterissuers"
- name: Install Consul
  kubernetes.core.helm:
    name: consul
    state: present
    chart_ref: hashicorp/consul
    update_repo_cache: true
    namespace: tools
    create_namespace: true
    timeout: 10m
    wait: true
    values_files:
      - "{{ kubernetes_cluster_config_path }}/helm-consul-values.yaml"
- name: Install Prometheus and Grafana
  kubernetes.core.helm:
    name: prometheus
    state: present
    chart_ref: prometheus-community/kube-prometheus-stack
    update_repo_cache: true
    namespace: observability
    create_namespace: true
    timeout: 10m
    wait: true
    values_files:
      - "{{ kubernetes_cluster_config_path }}/helm-prometheus-stack-values.yaml"
- name: Install MinIO
  kubernetes.core.helm:
    name: minio
    state: present
    chart_ref: minio/minio
    update_repo_cache: true
    namespace: tools
    create_namespace: true
    timeout: 10m
    wait: true
    values_files:
      - "{{ kubernetes_cluster_config_path }}/helm-minio-values.yaml"
# ## Helm chart have a bug that does not allow to remove the 'Hard node anti-affinity'
# ## For now, I generated the files and removed 'affinity' using kustomize.
- name: Install Loki
  kubernetes.core.k8s:
    definition: "{{ lookup('kubernetes.core.kustomize', dir=kustomize_files_path) }}"
  vars:
    kustomize_files_path: "{{ kubernetes_project_path }}/apps/loki"
- name: Install Grafana Agent Flow
  kubernetes.core.helm:
    name: grafana-agent-flow
    state: present
    chart_ref: grafana/grafana-agent
    update_repo_cache: true
    namespace: observability
    create_namespace: true
    timeout: 10m
    wait: true
    values_files:
      - "{{ kubernetes_cluster_config_path }}/helm-grafana-agent-flow-values.yaml"
- name: Install Vault
  kubernetes.core.helm:
    name: vault
    state: present
    chart_ref: hashicorp/vault
    update_repo_cache: true
    namespace: tools
    create_namespace: true
    timeout: 10m
    wait: true
    values_files:
      - "{{ kubernetes_cluster_config_path }}/helm-vault-values.yaml"
- name: Install Trivy
  kubernetes.core.helm:
    name: trivy-operator
    state: present
    chart_ref: aqua/trivy-operator
    update_repo_cache: true
    namespace: tools
    create_namespace: true
    timeout: 10m
    wait: true
    values_files:
      - "{{ kubernetes_cluster_config_path }}/helm-trivy-values.yaml"
