---
- name: Install Prometheus CRDs
  kubernetes.core.helm:
    name: prometheus-crds
    state: present
    chart_ref: prometheus-community/kube-prometheus-stack
    update_repo_cache: true
    namespace: observability
    create_namespace: true
    timeout: 10m
    wait: true
    values_files:
      - "{{ kubernetes_cluster_config_path }}/helm-prometheus-crds-values.yaml"
- name: Install cert-manager helm chart
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    chart_version: v1.12.0
    namespace: security
    create_namespace: true
    timeout: 10m
    state: present
    wait: true
    values_files:
      - "{{ kubernetes_cluster_config_path }}/helm-cert-manager-values.yaml"
- name: Configure cert-manager cluster issuer
  kubernetes.core.k8s:
    definition: "{{ lookup('kubernetes.core.kustomize', dir=kustomize_files_path) }}"
  vars:
    kustomize_files_path: "{{ project_bootstrap_kustomize_path }}/clusterissuers"
- name: Install Consul
  kubernetes.core.helm:
    name: consul
    chart_ref: hashicorp/consul
    namespace: tools
    create_namespace: true
    timeout: 10m
    state: present
    wait: true
    values_files:
      - "{{ kubernetes_cluster_config_path }}/helm-consul-values.yaml"
- name: Install Prometheus and Grafana
  kubernetes.core.helm:
    name: prometheus
    state: present
    chart_ref: prometheus-community/kube-prometheus-stack
    update_repo_cache: true
    namespace: observability
    create_namespace: true
    timeout: 10m
    wait: true
    values_files:
      - "{{ kubernetes_cluster_config_path }}/helm-prometheus-stack-values.yaml"
- name: Install MinIO
  kubernetes.core.helm:
    name: minio
    state: present
    chart_ref: minio/minio
    namespace: tools
    create_namespace: true
    timeout: 10m
    wait: true
    values_files:
      - "{{ kubernetes_cluster_config_path }}/helm-minio-values.yaml"
- name: Install Loki
  kubernetes.core.helm:
    name: loki
    chart_ref: grafana/loki
    namespace: observability
    create_namespace: true
    timeout: 10m
    state: present
    wait: true
    values_files:
      - "{{ kubernetes_cluster_config_path }}/helm-loki-values.yaml"
- name: Install Grafana Agent Flow
  kubernetes.core.helm:
    name: grafana-agent-flow
    chart_ref: grafana/grafana-agent
    namespace: observability
    create_namespace: true
    timeout: 10m
    state: present
    wait: true
    values_files:
      - "{{ kubernetes_cluster_config_path }}/helm-grafana-agent-flow-values.yaml"
- name: Install Vault
  kubernetes.core.helm:
    name: vault
    chart_ref: hashicorp/vault
    namespace: tools
    create_namespace: true
    timeout: 10m
    state: present
    wait: true
    values_files:
      - "{{ kubernetes_cluster_config_path }}/helm-vault-values.yaml"
- name: Install Trivy
  kubernetes.core.helm:
    name: trivy
    chart_ref: aqua/trivy-operator
    namespace: tools
    create_namespace: true
    timeout: 10m
    state: present
    wait: true
    values_files:
      - "{{ kubernetes_cluster_config_path }}/helm-trivy-values.yaml"
