---
- name: Install Helm Diff
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
    state: present
- name: Add jetstack chart repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io
- name: Add hashicorp chart repo
  kubernetes.core.helm_repository:
    name: hashicorp
    repo_url: https://helm.releases.hashicorp.com
- name: Add prometheus-community chart repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts
- name: Add grafana chart repo
  kubernetes.core.helm_repository:
    name: grafana
    repo_url: https://grafana.github.io/helm-charts
- name: Add opa chart repo
  kubernetes.core.helm_repository:
    name: opa
    repo_url: https://open-policy-agent.github.io/kube-mgmt/charts
- name: Add aqua chart repo (for Trivy operator)
  kubernetes.core.helm_repository:
    name: aqua
    repo_url: https://aquasecurity.github.io/helm-charts/
- name: Add minio chart repo
  kubernetes.core.helm_repository:
    name: minio
    repo_url: https://charts.min.io/
