---
# When running instances on your laptop, the time can easily go out of sync (e.g.
# when your computer goes to sleep or a instances is suspended).
# It's not really a problem in development, but we sync the time to avoid errors
# (for example, from apt).
- name: Restart chrony to ensure datetime sync
  ansible.builtin.systemd_service:
    name: chrony.service
    state: restarted
  changed_when: false
  register: chrony_restart_result
  # Ignore error when chrony not yet installed
  failed_when:
    - chrony_restart_result.msg is defined
    - "'Could not find' not in chrony_restart_result.msg"
