---
# Helm installation from
# https://helm.sh/docs/intro/install/#from-apt-debianubuntu
# Kustomize from
# https://kubectl.docs.kubernetes.io/installation/kustomize/binaries/

- name: Install Kubernetes clients CLI
  tags:
    - kubernetes_client
  block:
    - name: Test variables are set correctly
      ansible.builtin.assert:
        that:
          - kubernetes_minor_version is defined
          - kubernetes_minor_version is string
          - kubernetes_gpg_keyring is defined
          - kubernetes_gpg_keyring is string
          - kustomize_version is defined
          - kustomize_version is string
        quiet: true
    - name: Add Helm Signing Certificate
      ansible.builtin.apt_key:
        url: https://baltocdn.com/helm/signing.asc
        state: present
    - name: Install apt-transport-https
      ansible.builtin.apt:
        name: apt-transport-https
        state: present
    - name: Add Helm Repository to APT Sources
      ansible.builtin.apt_repository:
        repo: deb https://baltocdn.com/helm/stable/debian all main
        state: present
        mode: u=rw,g=r,o=r
        update_cache: true
    - name: Install Helm client
      ansible.builtin.apt:
        name: helm
        state: present
    - name: Add kubectl Signing Certificate
      ansible.builtin.apt_key:
        url: https://pkgs.k8s.io/core:/stable:/{{ kubernetes_minor_version }}/deb/Release.key
        keyring: "{{ kubernetes_gpg_keyring }}"
        state: present
    - name: Add the Kubernetes Repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by={{ kubernetes_gpg_keyring }}] https://pkgs.k8s.io/core:/stable:/{{ kubernetes_minor_version }}/deb/ /"
        filename: kubernetes
        mode: u=rw,g=r,o=r
        update_cache: true
    - name: Install kubectl client
      ansible.builtin.apt:
        name: kubectl
        state: present
    - name: Download kustomize installer
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh
        dest: /usr/local/bin/install_kustomize.sh
        mode: u=rwx,g=rx,o=r
    - name: Install kustomize client
      ansible.builtin.command:
        argv:
          - /usr/local/bin/install_kustomize.sh
          - "{{ kustomize_version }}"
        chdir: /usr/local/bin
        creates: /usr/local/bin/kustomize
