---
- name: Ensure basic dependencies are installed
  ansible.builtin.apt:
    pkg:
      - git
      - acl
      - golang-go
      - chrony
      - ca-certificates
      - snapd
- name: Install python libraries using apt
  when:
    - python_libraries is defined
    - python_libraries is iterable
    - python_libraries is not string
  ansible.builtin.apt:
    pkg: python3-{{ library }}
  loop: "{{ python_libraries | default([]) }}"
  loop_control:
    loop_var: library
- name: Install k8s clients
  ansible.builtin.import_tasks: install_k8s_clients.yaml
- name: Configure Go
  ansible.builtin.blockinfile:
    path: ~{{ ansible_user }}/.profile
    block: |
      export GOPATH=$HOME/go
      export GOBIN=$GOPATH/bin
      export PATH=$PATH:$GOPATH/bin:/usr/local/go/bin
