apiVersion: v1
kind: Namespace
metadata:
  name: tools
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: notary
---
apiVersion: v1
kind: Namespace
metadata:
  name: harbor-demo
