apiVersion: v1
kind: Service
metadata:
  labels:
    app: harbor
  name: harbor-registry
spec:
  ports:
  - name: https-registry
    port: 5443
  - name: https-controller
    port: 8443
  - name: https-metrics
    port: 8001
  selector:
    app: harbor
    component: registry
