---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app: harbor
    component: registry
  name: harbor-registry
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
