---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app: memcached
    app.kubernetes.io/component: memcached-server
- includeSelectors: false
  pairs:
    app.kubernetes.io/version: "1.6.23"
resources:
- service.yaml
- statefulset.yaml
