---
apiVersion: v1
kind: Service
metadata:
  name: memcached
spec:
  ports:
  - name: memcached-port
    port: 11211
    targetPort: 11211
  - name: http-metrics
    port: 9150
    targetPort: http-metrics
