---
apiVersion: v1
kind: Service
metadata:
  name: memcached-svc-headless
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: memcached
  ports:
  - name: memcached-port
    port: 11211
    protocol: TCP
    targetPort: memcached-port
  - name: http-metrics
    port: 9150
    protocol: TCP
    targetPort: http-metrics
