---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: memcached
  replicas: 1
  serviceName: memcached-svc-headless
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: memcached
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9150'
    spec:
      terminationGracePeriodSeconds: 180
      containers:
      - name: memcached
        image: memcached:1.6-alpine
        imagePullPolicy: Always
        ports:
        - name: memcached-port
          containerPort: 11211
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: memcached-port
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: memcached-port
          initialDelaySeconds: 5
          timeoutSeconds: 2
      - name: metrics
        image: quay.io/prometheus/memcached-exporter:latest
        imagePullPolicy: Always
        ports:
        - name: http-metrics
          containerPort: 9150
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 100Mi
