apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app: harbor
    component: jobservice
  name: harbor-jobservice
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
