---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: harbor
    component: jobservice
  name: harbor-jobservice
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: harbor
      component: jobservice
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: harbor
        component: jobservice
    spec:
      automountServiceAccountToken: false
      containers:
      - env:
        - name: CORE_SECRET
          valueFrom:
            secretKeyRef:
              key: secret
              name: harbor-core
        - name: INTERNAL_TLS_ENABLED
          value: "true"
        - name: INTERNAL_TLS_KEY_PATH
          value: /etc/harbor/ssl/jobservice/tls.key
        - name: INTERNAL_TLS_CERT_PATH
          value: /etc/harbor/ssl/jobservice/tls.crt
        - name: INTERNAL_TLS_TRUST_CA_PATH
          value: /etc/harbor/ssl/jobservice/ca.crt
        envFrom:
        - configMapRef:
            name: harbor-jobservice-env
        - secretRef:
            name: harbor-jobservice
        image: goharbor/harbor-jobservice:v2.5.2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
        livenessProbe:
          httpGet:
            path: /api/v1/stats
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 300
          periodSeconds: 10
        name: jobservice
        ports:
        - containerPort: 8443
        readinessProbe:
          httpGet:
            path: /api/v1/stats
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - mountPath: /etc/jobservice/config.yml
          name: jobservice-config
          subPath: config.yml
        - mountPath: /var/log/jobs
          name: job-logs
        - mountPath: /etc/harbor/ssl/jobservice
          name: jobservice-internal-certs
      securityContext:
        fsGroup: 10000
        runAsUser: 10000
      terminationGracePeriodSeconds: 120
      volumes:
      - configMap:
          name: harbor-jobservice
        name: jobservice-config
      - name: job-logs
        persistentVolumeClaim:
          claimName: harbor-jobservice
      - name: jobservice-internal-certs
        secret:
          secretName: harbor-jobservice-internal-tls
