apiVersion: v1
kind: Service
metadata:
  labels:
    app: harbor
  name: harbor-jobservice
spec:
  ports:
  - name: https-jobservice
    port: 443
    targetPort: 8443
  - name: https-metrics
    port: 8001
  selector:
    app: harbor
    component: jobservice
