---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tempo-ingester
  labels:
    app.kubernetes.io/name: tempo-ingester
    app.kubernetes.io/component: ingester
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: ingester
  maxUnavailable: 1
