---
# Source: tempo-distributed/templates/ingester/statefulset-ingester.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tempo-ingester
  labels:
    app.kubernetes.io/component: ingester
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: ingester
  serviceName: ingester
  podManagementPolicy: Parallel
  updateStrategy:
    rollingUpdate:
      partition: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/component: ingester
    spec:
      serviceAccountName: tempo
      securityContext:
        fsGroup: 1000
      enableServiceLinks: false

      containers:
      - args:
        - -target=ingester
        - -config.file=/conf/tempo.yaml
        - -mem-ballast-size-mbs=1024
        image: docker.io/grafana/tempo:2.3.1
        imagePullPolicy: IfNotPresent
        name: ingester
        ports:
        - name: grpc
          containerPort: 9095
        - name: http-memberlist
          containerPort: 7946
        - name: http-metrics
          containerPort: 3100
        readinessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 30
          timeoutSeconds: 1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
        volumeMounts:
        - mountPath: /conf
          name: config
        - mountPath: /runtime-config
          name: runtime-config
        - mountPath: /var/tempo
          name: data
      terminationGracePeriodSeconds: 300
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/component: ingester
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: ingester
              topologyKey: kubernetes.io/hostname
          - weight: 75
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: ingester
              topologyKey: topology.kubernetes.io/zone
      volumes:
      - name: config
        configMap:
          name: tempo-config
          items:
          - key: "tempo.yaml"
            path: "tempo.yaml"
      - name: runtime-config
        configMap:
          name: tempo-runtime
          items:
          - key: "overrides.yaml"
            path: "overrides.yaml"
      - name: data
        emptyDir: {}
