apiVersion: v1
kind: Service
metadata:
  name: notary-server
  namespace: tools
  labels:
    component: notary-server
spec:
  ports:
    - port: 4443
  selector:
    app: notary
    component: notary-server
