---
- name: Check that all nodes are ready
  when:
    - k3s_control_planes
    - ("flannel-backend" not in k3s_runtime_config or k3s_runtime_config["flannel-backend"] != "none")
    - not ansible_check_mode
  become: "{{ k3s_become }}"
  changed_when: false
  retries: 30
  delay: 5
  until:
    - kubectl_get_nodes_result.rc == 0
    - kubectl_get_nodes_result.stdout.find("NotReady") == -1
  ansible.builtin.command:
    cmd: "{{ k3s_install_dir }}/kubectl get nodes"
  failed_when: >-
    kubectl_get_nodes_result.stdout.find("was refused") != -1 or
    kubectl_get_nodes_result.stdout.find("ServiceUnavailable") != -1
  register: kubectl_get_nodes_result
