---
connectors:
- id: ldap
  name: OpenLDAP
  type: ldap
  config:
    bindDN: cn=admin,dc=iam-demo,dc=test
    bindPW: adminpassword
    groupSearch:
      baseDN: ou=Groups,dc=iam-demo,dc=test
      filter: (objectClass=groupOfNames)
      nameAttr: cn
      userMatchers:
      - groupAttr: member
        userAttr: DN
    host: terrakube-openldap-svc:1389
    insecureNoSSL: true
    userSearch:
      baseDN: ou=users,dc=iam-demo,dc=test
      emailAttr: mail
      filter: (objectClass=person)
      idAttr: DN
      nameAttr: cn
      username: mail
    usernamePrompt: Email Address
issuer: https://terrakube-api.iam-demo.test/dex
oauth2:
  responseTypes:
  - code
  - token
  - id_token
staticClients:
- id: iamdemo-app
  name: iamdemo-app
  public: true
  redirectURIs:
  - https://terrakube-ui.iam-demo.test
  - /device/callback
  - http://localhost:10000/login
  - http://localhost:10001/login
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  allowedOrigins:
  - '*'
  http: 0.0.0.0:5556
  skipApprovalScreen: true
