---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  template:
    spec:
      containers:
      - name: redis
        imagePullPolicy: Always
        args: ["--requirepass", "$(REDIS_PASSWORD)"]
        ports:
        - containerPort: 6379
          name: redis-prod
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PASSWORD
              name: terrakube-redis-env-secret
