apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
  namespace: devops
  labels:
    app: gitea
data:
  DISABLE_REGISTRATION: "true"
  DOMAIN: git.aim-demo.test
  HTTP_PORT: "3000"
  ROOT_URL: https://git.aim-demo.test
  RUN_MODE: "prod"
  SSH_PORT: "22"
